<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
$u=require_role(['owner','admin','manager']);
$msg=null;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  verify_csrf(); $orderId=(int)($_POST['order_id']??0); if($orderId<=0)throw new RuntimeException('Invalid order.');
  $key=trim((string)($_POST['license_key']??'')); $domain=trim((string)($_POST['domain']??''))?:null; $expires=trim((string)($_POST['expires_at']??''))?:null;
  $status=in_array($_POST['status']??'', ['active','suspended','expired','cancelled','available'],true)?$_POST['status']:'active';
  if($key==='')throw new RuntimeException('License key is required.');
  $db->beginTransaction();
  $q=$db->prepare('SELECT o.*,p.name package_name FROM orders o JOIN packages p ON p.id=o.package_id WHERE o.id=? FOR UPDATE');$q->execute([$orderId]);$o=$q->fetch();
  if(!$o)throw new RuntimeException('Order not found.');
  $oldKey=null;$licenseId=(int)($o['license_id']??0);
  if($licenseId){
   $q=$db->prepare('SELECT * FROM licenses WHERE id=? FOR UPDATE');$q->execute([$licenseId]);$lic=$q->fetch();if(!$lic)throw new RuntimeException('Linked license was not found.');$oldKey=$lic['license_key'];
   $q=$db->prepare('SELECT id FROM licenses WHERE license_key=? AND id<>? LIMIT 1');$q->execute([$key,$licenseId]);if($q->fetch())throw new RuntimeException('That license key already exists.');
   $db->prepare('UPDATE licenses SET license_key=?,domain=?,status=?,expires_at=?,reseller_id=?,package_id=? WHERE id=?')->execute([$key,$domain,$status,$expires,$o['reseller_id'],$o['package_id'],$licenseId]);
   $db->prepare('INSERT INTO license_history(license_id,user_id,action,old_domain,new_domain,notes) VALUES(?,?,?,?,?,?)')->execute([$licenseId,$u['id'],'admin_license_edited',$lic['domain'],$domain,'License key '.($oldKey===$key?'kept':'replaced').' by admin'.($oldKey!==$key?' | old key: '.$oldKey:'')]);
  }else{
   $q=$db->prepare('SELECT id FROM licenses WHERE license_key=? LIMIT 1');$q->execute([$key]);if($q->fetch())throw new RuntimeException('That license key already exists.');
   $db->prepare('INSERT INTO licenses(provider_account_id,license_key,domain,reseller_id,status,purchase_date,cost,expires_at,package_id) VALUES(NULL,?,?,?,?,CURDATE(),NULL,?,?)')->execute([$key,$domain,$o['reseller_id'],$status,$expires,$o['package_id']]);
   $licenseId=(int)$db->lastInsertId();
   $db->prepare('INSERT INTO license_history(license_id,user_id,action,old_domain,new_domain,notes) VALUES(?,?,?,?,?,?)')->execute([$licenseId,$u['id'],'license_attached_to_order',null,$domain,'License manually attached to order #'.$orderId]);
  }
  $db->prepare('UPDATE orders SET license_id=?,domain=?,status="completed",completed_at=COALESCE(completed_at,NOW()),notes=CONCAT(COALESCE(notes,""),?) WHERE id=?')->execute([$licenseId,$domain,"\nAdmin license edit on ".date('Y-m-d H:i:s'),$orderId]);
  $db->commit();audit('order_license_edited','orders',$orderId,'License ID '.$licenseId.($oldKey!==null&&$oldKey!==$key?' key replaced':' key updated'));$msg='Order #'.$orderId.' updated successfully.';
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}
}
$orderId=(int)($_GET['id']??$_POST['order_id']??0);
$orders=$db->query("SELECT o.id,o.status,o.amount,o.domain,o.license_id,o.created_at,r.name reseller_name,p.name package_name FROM orders o JOIN resellers r ON r.id=o.reseller_id JOIN packages p ON p.id=o.package_id ORDER BY o.id DESC LIMIT 100")->fetchAll();
$order=null;$license=null;
if($orderId){$q=$db->prepare('SELECT o.*,r.name reseller_name,p.name package_name FROM orders o JOIN resellers r ON r.id=o.reseller_id JOIN packages p ON p.id=o.package_id WHERE o.id=?');$q->execute([$orderId]);$order=$q->fetch();if($order&&$order['license_id']){$q=$db->prepare('SELECT * FROM licenses WHERE id=?');$q->execute([(int)$order['license_id']]);$license=$q->fetch();}}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Order & License Editor — SkyNoc</title><link rel="stylesheet" href="/admin-page-ui.css"><style>body{background:#f5f7fb}.wrap{max-width:1200px;margin:auto;padding:24px}.top{padding:14px 20px;display:flex;justify-content:space-between}.top a{margin-left:12px}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.card{background:#fff;border:1px solid #e4e7ec;border-radius:18px;padding:20px}.table-wrap{overflow:auto}.table{width:100%;min-width:650px;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #eaecf0;text-align:left;font-size:13px}.table th{font-size:11px;color:#667085}.btn{background:#465fff;color:#fff;border:0;border-radius:9px;padding:9px 13px;font-weight:800;text-decoration:none;cursor:pointer}.msg,.err{padding:12px;border-radius:10px;margin-bottom:14px}.msg{background:#ecfdf3;color:#067647}.err{background:#fef3f2;color:#b42318}.field{margin-bottom:13px}.field label{display:block;font-size:12px;font-weight:800;margin-bottom:5px;color:#344054}.field input,.field select{width:100%;box-sizing:border-box;padding:10px;border:1px solid #d0d5dd;border-radius:9px}.hero{background:linear-gradient(135deg,#101828,#344054,#465fff);color:#fff;border-radius:20px;padding:24px;margin-bottom:16px}.hero h1{margin:5px 0}.hero p{margin:0;color:#dbe4ff}@media(max-width:850px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="top"><strong>SkyNoc / Order & License Editor</strong><span><a href="/admin/dashboard">Dashboard</a><a href="/admin/orders">Orders</a><a href="/admin/licenses">Licenses</a><a href="/logout">Logout</a></span></div><div class="wrap"><div class="hero"><div style="font-size:11px;font-weight:800;letter-spacing:.08em;opacity:.8">FULFILLMENT CONTROL</div><h1>Order & License Editor</h1><p>After an order is active/completed, staff can enter a license key, replace an existing key, change the domain, status or expiry.</p></div><?php if($msg): ?><div class="msg">✓ <?=e($msg)?></div><?php endif; ?><?php if($error): ?><div class="err">! <?=e($error)?></div><?php endif; ?><div class="grid"><div class="card"><h2>Recent Orders</h2><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Reseller</th><th>Package</th><th>Amount</th><th>License</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($orders as $o): ?><tr><td>#<?=e((string)$o['id'])?></td><td><?=e($o['reseller_name'])?></td><td><?=e($o['package_name'])?></td><td>$<?=number_format((float)$o['amount'],2)?></td><td><?=e($o['license_id']?'#'.$o['license_id']:'Not assigned')?></td><td><?=e($o['status'])?></td><td><a class="btn" href="/admin/order-edit?id=<?=e((string)$o['id'])?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></div><div class="card"><h2><?= $order ? 'Edit Order #'.e((string)$order['id']) : 'Select an order' ?></h2><?php if($order): ?><p style="font-size:12px;color:#667085">Reseller: <b><?=e($order['reseller_name'])?></b> · Package: <b><?=e($order['package_name'])?></b> · Sales: <b>$<?=number_format((float)$order['amount'],2)?></b></p><form method="post"><?=csrf_field()?><input type="hidden" name="order_id" value="<?=e((string)$order['id'])?>"><div class="field"><label>License Key</label><input required name="license_key" value="<?=e($license['license_key']??'')?>" placeholder="Enter or replace WHMCS license key"></div><div class="field"><label>Domain</label><input name="domain" value="<?=e($license['domain']??$order['domain']??'')?>" placeholder="example.com"></div><div class="field"><label>Expires At</label><input type="datetime-local" name="expires_at" value="<?=e($license && $license['expires_at'] ? date('Y-m-d\\TH:i',strtotime($license['expires_at'])) : '')?>"></div><div class="field"><label>License Status</label><select name="status"><?php foreach(['active','suspended','expired','cancelled','available'] as $s): ?><option value="<?=e($s)?>" <?=($license['status']??'active')===$s?'selected':''?>><?=e(ucfirst($s))?></option><?php endforeach; ?></select></div><button class="btn" type="submit">Save Order & License</button></form><?php else: ?><p style="color:#667085">Choose an order from the list to edit its license assignment.</p><?php endif; ?></div></div></div></body></html>
