<?php
require __DIR__ . '/../app/bootstrap.php';
$u = require_role(['owner','admin']);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Settings — SkyNoc Admin</title><link rel="stylesheet" href="/admin-page-ui.css"><style>
:root{--blue:#465fff;--ink:#101828;--muted:#667085;--line:#e4e7ec}.hero{position:relative;overflow:hidden;background:linear-gradient(135deg,#111827 0%,#172554 58%,#1d4ed8 100%);color:#fff;border-radius:22px;padding:30px;margin-bottom:20px;box-shadow:0 18px 45px rgba(16,24,40,.16)}.hero:after{content:"";position:absolute;width:240px;height:240px;border-radius:50%;right:-80px;top:-110px;background:rgba(255,255,255,.08)}.hero>*{position:relative;z-index:1}.eyebrow{display:inline-flex;padding:6px 10px;border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.08);border-radius:999px;font-size:11px;font-weight:800;letter-spacing:.05em}.hero h1{font-size:32px;margin:14px 0 7px;letter-spacing:-.04em}.hero p{max-width:720px;margin:0;color:rgba(255,255,255,.78);font-size:14px;line-height:1.7}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.setting-card{display:flex;flex-direction:column;min-height:170px;padding:20px!important;border-radius:18px!important;text-decoration:none!important;color:var(--ink)!important;border:1px solid var(--line);transition:transform .16s,box-shadow .16s,border-color .16s;background:#fff}.setting-card:hover{transform:translateY(-2px);box-shadow:0 12px 28px rgba(16,24,40,.08);border-color:#c7d2fe}.icon{width:44px;height:44px;display:grid;place-items:center;border-radius:13px;background:#eef2ff;color:var(--blue);font-size:20px;margin-bottom:15px}.setting-card h2{font-size:16px;margin:0 0 6px}.setting-card p{font-size:12px;line-height:1.6;color:var(--muted);margin:0}.open{margin-top:auto;padding-top:15px;font-size:11px;font-weight:800;color:var(--blue)}.section-title{display:flex;justify-content:space-between;align-items:end;margin:24px 0 11px}.section-title h3{margin:0;font-size:15px}.section-title span{font-size:11px;color:var(--muted)}.quick{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.quick a{padding:13px;border:1px solid var(--line);border-radius:13px;background:#fff;text-decoration:none;color:#344054;font-size:12px;font-weight:750}.quick a:hover{border-color:#c7d2fe;color:var(--blue)}.note{margin-top:18px;padding:14px 16px;border:1px solid #dbe5ff;background:#f8faff;border-radius:14px;font-size:12px;line-height:1.6;color:#475467}.top a{margin-left:5px}@media(max-width:980px){.cards{grid-template-columns:repeat(2,1fr)}.quick{grid-template-columns:repeat(2,1fr)}}@media(max-width:620px){.cards,.quick{grid-template-columns:1fr}.hero{padding:23px 18px;border-radius:18px}.hero h1{font-size:26px}.wrap{padding:18px 12px!important}}
</style></head><body><div class="top"><strong>SkyNoc <span style="opacity:.55">/</span> Admin</strong><span><?=e($u['name'])?> · <a href="/admin">Dashboard</a> · <a href="/logout">Logout</a></span></div><div class="wrap">
<div class="hero"><span class="eyebrow">⚙️ ADMIN CONTROL CENTER</span><h1>Settings</h1><p>All platform configuration is now organized into separate settings pages. Open only the section you need instead of managing everything from one long form.</p></div>
<div class="cards"><a class="setting-card" href="/admin/settings/payments"><div class="icon">💳</div><h2>Payment Methods</h2><p>Enable or disable deposit methods, minimum deposits, instructions and USDT/BSC verification settings.</p><span class="open">Open Payment Settings →</span></a>
<a class="setting-card" href="/admin/settings/telegram"><div class="icon">✈️</div><h2>Telegram</h2><p>Manage License Control Bot and the separate reseller deposit notification bot.</p><span class="open">Open Telegram Settings →</span></a>
<a class="setting-card" href="/admin/settings/smtp"><div class="icon">✉️</div><h2>SMTP / Email</h2><p>Configure platform SMTP host, port, encryption, sender identity and test email delivery.</p><span class="open">Open SMTP Settings →</span></a>
<a class="setting-card" href="/admin/settings/discord"><div class="icon">◉</div><h2>Discord</h2><p>Manage the platform Discord webhook and notification channel configuration.</p><span class="open">Open Discord Settings →</span></a>
<a class="setting-card" href="/admin/settings/binance"><div class="icon">₿</div><h2>Binance / Crypto</h2><p>Configure the existing Binance and crypto payment integration settings.</p><span class="open">Open Binance Settings →</span></a>
<a class="setting-card" href="/admin/reseller-levels"><div class="icon">🏆</div><h2>Reseller Levels</h2><p>Manage reseller levels, license counts, pricing discounts and level-based commercial rules.</p><span class="open">Open Reseller Levels →</span></a>
<a class="setting-card" href="/admin/hostname"><div class="icon">🌐</div><h2>Hostname Product</h2><p>Manage SkyNoc hostname product configuration, pricing and hostname inventory.</p><span class="open">Open Hostname Settings →</span></a>
<a class="setting-card" href="/security"><div class="icon">🔐</div><h2>Security</h2><p>Open the account security and authentication controls for the current administrator.</p><span class="open">Open Security →</span></a>
<a class="setting-card" href="/admin/reports"><div class="icon">📊</div><h2>Reports</h2><p>Review platform activity and operational reports without mixing them into configuration.</p><span class="open">Open Reports →</span></a></div>
<div class="section-title"><h3>Quick Access</h3><span>Frequently used admin tools</span></div><div class="quick"><a href="/admin">← Admin Dashboard</a><a href="/admin/coupons">🎟 Coupons</a><a href="/admin/order-fulfill">📦 Order Fulfillment</a><a href="/admin/renew">🔄 Renewals</a></div><div class="note">Settings are intentionally separated by function. This reduces accidental changes and makes the admin panel easier to use on mobile and desktop.</div>
</div></body></html>
