<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
$u=require_role(['owner','admin','manager']);
$msg=null;$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{verify_csrf();$id=(int)($_POST['id']??0);$buy=(float)($_POST['buy_price']??-1);$sale=(float)($_POST['sales_price']??-1);if($id<=0||$buy<0||$sale<=0)throw new RuntimeException('Buy price must be 0 or more and sales price must be greater than 0.');if($buy>$sale)throw new RuntimeException('Buy price cannot be greater than sales price.');$db->prepare('UPDATE packages SET buy_price=?,price=? WHERE id=?')->execute([$buy,$sale,$id]);audit('package_pricing_updated','packages',$id,'Buy '.$buy.' / Sales '.$sale);$msg='Package pricing updated.';}catch(Throwable $e){$error=$e->getMessage();}}
$packages=$db->query('SELECT id,name,slug,price,buy_price,billing_period,active FROM packages ORDER BY sort_order,id')->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Package Pricing — SkyNoc</title><link rel="stylesheet" href="/admin-page-ui.css"><style>body{background:#f5f7fb}.wrap{max-width:1050px;margin:auto;padding:24px}.top{padding:14px 20px;display:flex;justify-content:space-between}.top a{margin-left:12px}.hero{background:linear-gradient(135deg,#101828,#344054,#465fff);color:#fff;border-radius:20px;padding:24px;margin-bottom:16px}.hero h1{margin:5px 0}.hero p{margin:0;color:#dbe4ff}.card{background:#fff;border:1px solid #e4e7ec;border-radius:18px;padding:20px}.table-wrap{overflow:auto}.table{width:100%;min-width:820px;border-collapse:collapse}.table th,.table td{padding:11px;border-bottom:1px solid #eaecf0;text-align:left;font-size:13px}.table th{font-size:11px;color:#667085}.field{width:110px;padding:8px;border:1px solid #d0d5dd;border-radius:8px}.btn{background:#465fff;color:#fff;border:0;border-radius:8px;padding:8px 11px;font-weight:800;cursor:pointer}.msg,.err{padding:12px;border-radius:10px;margin-bottom:14px}.msg{background:#ecfdf3;color:#067647}.err{background:#fef3f2;color:#b42318}.profit{font-weight:800;color:#067647}</style></head><body><div class="top"><strong>SkyNoc / Package Pricing</strong><span><a href="/admin/dashboard">Dashboard</a><a href="/admin/packages">Packages</a><a href="/logout">Logout</a></span></div><div class="wrap"><div class="hero"><div style="font-size:11px;font-weight:800;letter-spacing:.08em;opacity:.8">PRICING CONTROL</div><h1>Buy Price & Sales Price</h1><p>Set the admin's upstream cost and reseller sales price for every WHMCS license package. Dashboard profit uses sales minus buy cost.</p></div><?php if($msg): ?><div class="msg">✓ <?=e($msg)?></div><?php endif; ?><?php if($error): ?><div class="err">! <?=e($error)?></div><?php endif; ?><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Package</th><th>Billing</th><th>Buy Price</th><th>Sales Price</th><th>Profit / Sale</th><th>Status</th><th>Save</th></tr></thead><tbody><?php foreach($packages as $p): $profit=(float)$p['price']-(float)$p['buy_price']; ?><tr><form method="post"><?=csrf_field()?><input type="hidden" name="id" value="<?=e((string)$p['id'])?>"><td><b><?=e($p['name'])?></b><br><small><?=e($p['slug'])?></small></td><td><?=e($p['billing_period'])?></td><td><input class="field" type="number" step="0.01" min="0" name="buy_price" value="<?=e((string)$p['buy_price'])?>"></td><td><input class="field" type="number" step="0.01" min="0.01" name="sales_price" value="<?=e((string)$p['price'])?>"></td><td class="profit">$<?=number_format($profit,2)?></td><td><?=((int)$p['active']===1?'Active':'Disabled')?></td><td><button class="btn" type="submit">Save</button></td></form></tr><?php endforeach; ?><?php if(!$packages): ?><tr><td colspan="7">No packages found. Create a package first.</td></tr><?php endif; ?></tbody></table></div></div></div></body></html>
