<?php
require __DIR__ . '/../app/bootstrap.php';
require __DIR__ . '/../app/order_manual.php';
$u=require_role(['owner','admin','manager','staff']);
if(!can('license.manage',$u)){http_response_code(403);exit('Forbidden');}
$msg=null;$error=null;
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf();$a=(string)($_POST['action']??'');
  if($a==='delete'){
   $id=(int)($_POST['id']??0);$q=$db->prepare("DELETE FROM licenses WHERE id=? AND status='available' AND reseller_id IS NULL");$q->execute([$id]);
   if($q->rowCount()!==1)throw new RuntimeException('Only unassigned Available inventory licenses can be deleted.');
   audit('license_deleted','licenses',$id,'inventory');$msg='License deleted from inventory.';
  }
  if($a==='edit'){
   $id=(int)($_POST['id']??0);$key=trim((string)($_POST['license_key']??''));$domain=trim((string)($_POST['domain']??''))?:null;$cost=($_POST['cost']??'')===''?null:(float)$_POST['cost'];$expires=trim((string)($_POST['expires_at']??''))?:null;$status=in_array($_POST['status']??'', ['available','active','suspended','expired','cancelled'],true)?$_POST['status']:'available';
   if($id<1||$key==='')throw new RuntimeException('License ID and key are required.');
   $q=$db->prepare('SELECT id FROM licenses WHERE license_key=? AND id<>? LIMIT 1');$q->execute([$key,$id]);if($q->fetchColumn())throw new RuntimeException('That license key already exists.');
   $db->prepare('UPDATE licenses SET license_key=?,domain=?,cost=?,expires_at=?,status=? WHERE id=?')->execute([$key,$domain,$cost,$expires,$status,$id]);
   audit('license_updated','licenses',$id,'inventory edit');$msg='License updated.';
  }
  if($a==='manual_activate'){
   $result=skynoc_manual_order($db,(int)($_POST['order_id']??0),(string)($_POST['license_key']??''),(int)$u['id']);
   $msg='Order #'.(int)($_POST['order_id']).' activated manually. License: '.$result['key'];
  }
 }
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();$error=$e->getMessage();}
$inventory=$db->query("SELECT l.*,r.name reseller_name,p.name package_name,pa.provider_name FROM licenses l LEFT JOIN resellers r ON r.id=l.reseller_id LEFT JOIN packages p ON p.id=l.package_id LEFT JOIN provider_accounts pa ON pa.id=l.provider_account_id WHERE l.status='available' AND l.reseller_id IS NULL ORDER BY l.id DESC LIMIT 200")->fetchAll();
$orders=$db->query("SELECT o.id,o.reseller_id,o.package_id,o.domain,o.amount,o.status,o.created_at,p.name package_name,r.name reseller_name,r.email reseller_email FROM orders o JOIN packages p ON p.id=o.package_id JOIN resellers r ON r.id=o.reseller_id WHERE o.status IN ('pending','processing') ORDER BY o.id ASC LIMIT 100")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>License Inventory — SkyNoc</title><link rel="stylesheet" href="/admin-page-ui.css"><style>.wrap{max-width:1400px;margin:auto}.hero{background:linear-gradient(135deg,#101828,#1d4ed8);color:#fff;border-radius:18px;padding:24px;margin-bottom:18px}.hero h1{margin:5px 0}.muted{color:#667085}.key{font:12px ui-monospace,monospace;word-break:break-all}.mini{min-width:90px!important;padding:8px 10px!important;font-size:12px}.danger-btn{background:#b42318!important}.editbox{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:8px;align-items:end}.order-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.small{font-size:12px;line-height:1.7}@media(max-width:900px){.editbox{grid-template-columns:1fr 1fr}.order-grid{grid-template-columns:1fr}}@media(max-width:600px){.editbox{grid-template-columns:1fr}.wrap{padding:0 12px!important}}</style></head><body><div class="top"><strong>SkyNoc / License Inventory</strong><span><?=e($u['name'])?> · <a href="/admin">Dashboard</a></span></div><div class="wrap"><div class="hero"><div style="font-size:11px;letter-spacing:.08em;font-weight:800;opacity:.8">MANUAL LICENSE CONTROL</div><h1>Inventory & Manual Activation</h1><div>Manage provider inventory yourself. Edit/delete unused keys, then manually activate the first order when you receive a key.</div></div><?php if($msg):?><div class="msg">✓ <?=e($msg)?></div><?php endif;?><?php if($error):?><div class="err">! <?=e($error)?></div><?php endif;?>
<section class="card"><h2>Available Inventory</h2><p class="muted">Delete is available only for unused, unassigned inventory. Edit lets you correct key, domain, cost, expiry or status.</p><div class="table"><table><thead><tr><th>ID</th><th>License</th><th>Provider</th><th>Package</th><th>Cost</th><th>Expiry</th><th>Actions</th></tr></thead><tbody><?php if(!$inventory):?><tr><td colspan="7">No available inventory licenses.</td></tr><?php endif;?><?php foreach($inventory as $l):?><tr><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="edit"><input type="hidden" name="id" value="<?=$l['id']?>"><td>#<?=$l['id']?></td><td><input class="key" name="license_key" value="<?=e($l['license_key'])?>" required><br><input name="domain" value="<?=e($l['domain']??'')?>" placeholder="domain"></td><td><?=e($l['provider_name']??'Manual')?></td><td><?=e($l['package_name']??'Unassigned')?></td><td><input style="max-width:100px" type="number" step="0.01" min="0" name="cost" value="<?=e((string)($l['cost']??''))?>"></td><td><input type="datetime-local" name="expires_at" value="<?=!empty($l['expires_at'])?e(date('Y-m-d\TH:i',strtotime($l['expires_at']))):''?>"></td><td><select name="status"><option value="available">Available</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select><button class="mini" type="submit">Save Edit</button></form><form method="post" style="display:inline;margin-top:6px" onsubmit="return confirm('Delete this unused license from inventory?')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$l['id']?>"><button class="mini danger-btn" type="submit">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card"><h2>Pending Orders — Manual Activation</h2><p class="muted">This is the first-time activation workflow. Enter the provider license key after the order is paid. The existing order amount has already been charged from the reseller wallet.</p><?php if(!$orders):?><div class="notice">No pending orders.</div><?php endif;?><?php foreach($orders as $o):?><div class="card" style="margin:12px 0"><div class="order-grid"><div class="small"><b>#<?=$o['id']?> · <?=e($o['package_name'])?></b><br>Reseller: <?=e($o['reseller_name'])?> (<?=e($o['reseller_email'])?>)<br>Domain: <?=e($o['domain'])?><br>Amount: $<?=number_format((float)$o['amount'],2)?> · Status: <?=e(strtoupper($o['status']))?><br>Order date: <?=e($o['created_at']??'-')?></div><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="manual_activate"><input type="hidden" name="order_id" value="<?=$o['id']?>"><label>Provider License Key</label><input name="license_key" required placeholder="Paste the real WHMCS license key"><button style="margin-top:10px" type="submit">Activate & Complete Order</button></form></div></div><?php endforeach;?></section><div class="page-footer">Manual first activation is supported. Future monthly/annual renewal can be handled from the reseller service page.</div></div></body></html>