<?php
require __DIR__ . '/../app/bootstrap.php';
$u=require_role(['owner','admin','manager','staff']);
$msg=null;
if($_SERVER['REQUEST_METHOD']==='POST'){ verify_csrf(); $a=$_POST['action']??'';
 if($a==='provider' && in_array($u['role'],['owner','admin','manager'],true)){ $s=$db->prepare('INSERT INTO provider_accounts(provider_type,provider_name,account_email,account_label,internal_notes) VALUES(?,?,?,?,?)');$s->execute([$_POST['provider_type']?:'MANUAL_PARTNER',trim($_POST['provider_name']),trim($_POST['account_email'])?:null,trim($_POST['account_label'])?:null,trim($_POST['internal_notes'])?:null]);audit('provider_created','provider_accounts',(int)$db->lastInsertId());$msg='Provider added.'; }
 if($a==='reseller' && in_array($u['role'],['owner','admin'],true)){ $name=trim($_POST['name']);$email=trim($_POST['email']);$pw=$_POST['password']; if(strlen($pw)>=10){$db->beginTransaction();$s=$db->prepare('INSERT INTO users(name,email,password_hash,role,status) VALUES(?,?,?,"reseller","active")');$s->execute([$name,$email,password_hash($pw,PASSWORD_DEFAULT)]);$uid=(int)$db->lastInsertId();$s=$db->prepare('INSERT INTO resellers(user_id,name,email) VALUES(?,?,?)');$s->execute([$uid,$name,$email]);$db->commit();audit('reseller_created','resellers',(int)$db->lastInsertId());$msg='Reseller created.';} }
 if($a==='license' && in_array($u['role'],['owner','admin','manager'],true)){ $s=$db->prepare('INSERT INTO licenses(provider_account_id,license_key,domain,reseller_id,status,purchase_date,cost,expires_at) VALUES(?,?,?,?,?,?,?,?)');$rid=$_POST['reseller_id']!==''?(int)$_POST['reseller_id']:null;$pid=$_POST['provider_account_id']!==''?(int)$_POST['provider_account_id']:null;$s->execute([$pid,trim($_POST['license_key']),trim($_POST['domain'])?:null,$rid,$_POST['status']?:'available',$_POST['purchase_date']?:null,$_POST['cost']!==''?$_POST['cost']:null,$_POST['expires_at']?:null]);audit('license_created','licenses',(int)$db->lastInsertId());$msg='License added.'; }
}
$providers=$db->query('SELECT id,provider_name,account_email,account_label,status FROM provider_accounts ORDER BY id DESC')->fetchAll();
$resellers=$db->query('SELECT id,name,email,status FROM resellers ORDER BY id DESC')->fetchAll();
$licenses=$db->query('SELECT l.*,r.name reseller_name,p.provider_name FROM licenses l LEFT JOIN resellers r ON r.id=l.reseller_id LEFT JOIN provider_accounts p ON p.id=l.provider_account_id ORDER BY l.id DESC LIMIT 100')->fetchAll();
$reissues=$db->query('SELECT rr.*,l.license_key,r.name reseller_name FROM reissue_requests rr JOIN licenses l ON l.id=rr.license_id JOIN resellers r ON r.id=rr.reseller_id ORDER BY rr.id DESC LIMIT 50')->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SkyNoc Admin</title><style>body{font-family:Arial;margin:0;background:#f5f7fa;color:#111827}.nav{background:#111827;color:#fff;padding:16px 24px}.wrap{max-width:1200px;margin:24px auto;padding:0 16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.card{background:#fff;padding:18px;border-radius:10px;box-shadow:0 2px 12px #0001}input,select,textarea,button{width:100%;box-sizing:border-box;padding:9px;margin:4px 0 8px}button{background:#111827;color:#fff;border:0;border-radius:5px}table{width:100%;border-collapse:collapse;background:#fff}td,th{padding:9px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.msg{background:#dcfce7;padding:10px;margin-bottom:15px}</style></head><body><div class="nav"><b>SkyNoc Admin</b> · <?=e($u['name'])?> (<?=e($u['role'])?>) · <a style="color:white" href="/dashboard.php">Dashboard</a> · <a style="color:white" href="/logout.php">Logout</a></div><div class="wrap"><h1>Management</h1><?php if($msg):?><div class="msg"><?=e($msg)?></div><?php endif;?><div class="grid">
<div class="card"><h3>Add Provider</h3><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="provider"><input name="provider_name" placeholder="Provider name" required><input name="account_email" type="email" placeholder="Upstream account email"><input name="account_label" placeholder="Internal account label"><select name="provider_type"><option>MANUAL_PARTNER</option><option>WHMCS_API</option></select><textarea name="internal_notes" placeholder="Internal notes"></textarea><button>Add Provider</button></form></div>
<div class="card"><h3>Create Reseller</h3><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="reseller"><input name="name" placeholder="Reseller name" required><input name="email" type="email" placeholder="Login email" required><input name="password" type="password" placeholder="Temporary password (10+ chars)" required><button>Create Reseller</button></form></div>
<div class="card"><h3>Add License</h3><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="license"><input name="license_key" placeholder="License key" required><input name="domain" placeholder="Domain"><select name="provider_account_id"><option value="">Provider account</option><?php foreach($providers as $p):?><option value="<?=$p['id']?>"><?=e($p['provider_name'].' — '.$p['account_label'])?></option><?php endforeach;?></select><select name="reseller_id"><option value="">Unassigned</option><?php foreach($resellers as $r):?><option value="<?=$r['id']?>"><?=e($r['name'])?></option><?php endforeach;?></select><select name="status"><option>available</option><option>active</option><option>suspended</option></select><input name="purchase_date" type="date"><input name="cost" type="number" step="0.01" placeholder="Cost"><input name="expires_at" type="datetime-local"><button>Add License</button></form></div></div>
<h2>Licenses</h2><table><tr><th>ID</th><th>License</th><th>Domain</th><th>Provider</th><th>Reseller</th><th>Status</th></tr><?php foreach($licenses as $l):?><tr><td><?=$l['id']?></td><td><?=e($l['license_key'])?></td><td><?=e($l['domain'])?></td><td><?=e($l['provider_name'])?></td><td><?=e($l['reseller_name'])?></td><td><?=e($l['status'])?></td></tr><?php endforeach;?></table><h2>Reissue Requests</h2><table><tr><th>ID</th><th>License</th><th>Reseller</th><th>Current</th><th>New</th><th>Status</th><th>Reason</th></tr><?php foreach($reissues as $r):?><tr><td><?=$r['id']?></td><td><?=e($r['license_key'])?></td><td><?=e($r['reseller_name'])?></td><td><?=e($r['current_domain'])?></td><td><?=e($r['new_domain'])?></td><td><?=e($r['status'])?></td><td><?=e($r['reason'])?></td></tr><?php endforeach;?></table></div></body></html>