<?php
require __DIR__ . '/../app/bootstrap.php';
$u = require_role(['owner','admin']);
$msg=null; $error=null;
try {
    if ($_SERVER['REQUEST_METHOD']==='POST') {
        verify_csrf();
        $lt=trim((string)($_POST['license_bot_token']??''));
        $lc=trim((string)($_POST['license_admin_chat_id']??''));
        if($lt===''||$lc==='') throw new RuntimeException('License Control Bot token and admin chat ID are required.');
        $dt=trim((string)($_POST['deposit_bot_token']??''));
        $dc=trim((string)($_POST['deposit_admin_chat_id']??''));
        $db->prepare('INSERT INTO telegram_settings(id,bot_token,admin_chat_id,license_bot_token,license_admin_chat_id,deposit_bot_token,deposit_admin_chat_id) VALUES(1,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE bot_token=VALUES(bot_token),admin_chat_id=VALUES(admin_chat_id),license_bot_token=VALUES(license_bot_token),license_admin_chat_id=VALUES(license_admin_chat_id),deposit_bot_token=VALUES(deposit_bot_token),deposit_admin_chat_id=VALUES(deposit_admin_chat_id)')
            ->execute([$lt,$lc,$lt,$lc,$dt?:null,$dc?:null]);
        $msg='Telegram settings saved successfully.';
    }
} catch(Throwable $e){$error=$e->getMessage();error_log('SkyNoc Telegram settings error: '.$e->getMessage());}
$tg=$db->query('SELECT * FROM telegram_settings WHERE id=1 LIMIT 1')->fetch()?:[];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Telegram Settings — SkyNoc</title><link rel="stylesheet" href="/admin-page-ui.css"><style>
:root{--blue:#465fff;--line:#e4e7ec;--muted:#667085}.hero{background:linear-gradient(135deg,#111827,#1d4ed8);color:#fff;border-radius:20px;padding:26px 28px;margin-bottom:18px}.hero h1{margin:8px 0;font-size:28px}.hero p{margin:0;color:#dbe5ff}.nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.nav a{padding:9px 12px;border:1px solid rgba(255,255,255,.18);border-radius:10px;color:#fff!important;background:rgba(255,255,255,.08);font-size:12px;font-weight:700}.card{padding:22px!important;border-radius:18px!important}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{border:1px solid var(--line);border-radius:16px;padding:18px;background:#fff}.panel h2{margin:0 0 5px;font-size:16px}.panel p{margin:0 0 16px;font-size:12px;color:var(--muted);line-height:1.6}.field{margin-bottom:14px}.field:last-child{margin-bottom:0}.field label{display:block;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:#475467;margin-bottom:6px}.field input{width:100%;box-sizing:border-box}.note{margin-top:16px;padding:13px;border:1px solid #fedf89;background:#fffaeb;border-radius:13px;color:#92400e;font-size:12px;line-height:1.6}.actions{display:flex;justify-content:flex-end;margin-top:18px;position:sticky;bottom:12px}.actions button{box-shadow:0 10px 26px rgba(70,95,255,.25)}@media(max-width:760px){.grid{grid-template-columns:1fr}.actions button{width:100%}}
</style></head><body><div class="top"><strong>SkyNoc / Admin</strong><span><?=e($u['name'])?> · <a href="/admin">Dashboard</a> · <a href="/logout">Logout</a></span></div><div class="wrap"><div class="hero"><div style="font-size:11px;font-weight:800;opacity:.75;letter-spacing:.08em">SETTINGS / TELEGRAM</div><h1>Telegram Operations</h1><p>Keep license-control and deposit notification bots separated so each workflow can be managed independently.</p><div class="nav"><a href="/admin/settings">⚙ Settings</a><a href="/admin/settings/payments">💳 Payments</a><a href="/admin/settings/discord">◉ Discord</a><a href="/admin/settings/binance">₿ Binance</a><a href="/admin/settings/smtp">✉ SMTP</a></div></div><?php if($msg):?><div class="msg">✓ <?=e($msg)?></div><?php endif;?><?php if($error):?><div class="err">! <?=e($error)?></div><?php endif;?><form method="post" class="card"><?=csrf_field()?><div class="grid"><section class="panel"><h2>License Control Bot</h2><p>Used for WHMCS license issue/re-issue and license related admin notifications.</p><div class="field"><label>Bot Token</label><input type="password" name="license_bot_token" value="<?=e((string)($tg['license_bot_token']??$tg['bot_token']??''))?>" autocomplete="new-password"></div><div class="field"><label>Admin Chat ID</label><input name="license_admin_chat_id" value="<?=e((string)($tg['license_admin_chat_id']??$tg['admin_chat_id']??''))?>"></div></section><section class="panel"><h2>Deposit Notification Bot</h2><p>Optional bot for reseller deposit and wallet notifications. Leave blank to disable this dedicated channel.</p><div class="field"><label>Bot Token</label><input type="password" name="deposit_bot_token" value="<?=e((string)($tg['deposit_bot_token']??''))?>" autocomplete="new-password"></div><div class="field"><label>Admin Chat ID</label><input name="deposit_admin_chat_id" value="<?=e((string)($tg['deposit_admin_chat_id']??''))?>"></div></section></div><div class="note">Security: bot tokens are credentials. Use HTTPS, do not post them in tickets or screenshots, and rotate a token immediately if it is exposed.</div><div class="actions"><button class="btn" type="submit">Save Telegram Settings</button></div></form></div></body></html>
