<?php
require __DIR__ . '/../app/bootstrap.php';
$u = require_role(['owner','admin']);
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Settings — SkyNoc Admin</title><link rel="stylesheet" href="/admin-page-ui.css">
<style>
:root{--blue:#465fff;--ink:#101828;--muted:#667085;--line:#e4e7ec;--bg:#f8fafc}body{background:var(--bg)}
.settings-shell{display:grid;grid-template-columns:235px minmax(0,1fr);gap:18px;align-items:start}.settings-menu{position:sticky;top:16px;background:#fff;border:1px solid var(--line);border-radius:18px;padding:12px;box-shadow:0 8px 24px rgba(16,24,40,.05)}
.menu-title{padding:9px 10px 12px;font-size:11px;font-weight:900;color:#98a2b3;text-transform:uppercase;letter-spacing:.08em}.menu-group{margin-bottom:10px}.menu-group:last-child{margin-bottom:0}.menu-label{padding:6px 10px;font-size:10px;font-weight:800;color:#98a2b3;text-transform:uppercase;letter-spacing:.05em}
.settings-menu a{display:flex;align-items:center;gap:10px;padding:10px;border-radius:10px;text-decoration:none;color:#344054;font-size:12px;font-weight:750;margin:2px 0}.settings-menu a:hover{background:#f5f7ff;color:var(--blue)}.settings-menu .active{background:#eef2ff;color:var(--blue)}.mi{width:28px;height:28px;border-radius:8px;display:grid;place-items:center;background:#f2f4f7;font-size:14px}.active .mi{background:#fff}
.content{min-width:0}.hero{position:relative;overflow:hidden;background:linear-gradient(135deg,#111827 0%,#172554 58%,#1d4ed8 100%);color:#fff;border-radius:22px;padding:30px;margin-bottom:18px;box-shadow:0 18px 45px rgba(16,24,40,.14)}.hero:after{content:"";position:absolute;width:250px;height:250px;border-radius:50%;right:-90px;top:-115px;background:rgba(255,255,255,.08)}.hero>*{position:relative;z-index:1}.eyebrow{display:inline-flex;padding:6px 10px;border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.08);border-radius:999px;font-size:10px;font-weight:900;letter-spacing:.06em}.hero h1{font-size:31px;margin:14px 0 7px;letter-spacing:-.04em}.hero p{max-width:720px;margin:0;color:rgba(255,255,255,.78);font-size:13px;line-height:1.7}
.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.setting-card{display:flex;align-items:flex-start;gap:14px;padding:18px!important;border-radius:16px!important;text-decoration:none!important;color:var(--ink)!important;border:1px solid var(--line);background:#fff;transition:.16s;min-height:104px}.setting-card:hover{transform:translateY(-2px);box-shadow:0 12px 28px rgba(16,24,40,.08);border-color:#c7d2fe}.icon{width:42px;height:42px;flex:0 0 42px;display:grid;place-items:center;border-radius:12px;background:#eef2ff;color:var(--blue);font-size:19px}.setting-card h2{font-size:15px;margin:1px 0 5px}.setting-card p{font-size:11px;line-height:1.55;color:var(--muted);margin:0}.arrow{margin-top:8px;font-size:10px;font-weight:900;color:var(--blue)}
.section-title{display:flex;justify-content:space-between;align-items:end;margin:22px 0 10px}.section-title h3{margin:0;font-size:14px}.section-title span{font-size:10px;color:var(--muted)}.quick{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.quick a{padding:12px;border:1px solid var(--line);border-radius:12px;background:#fff;text-decoration:none;color:#344054;font-size:11px;font-weight:750}.quick a:hover{border-color:#c7d2fe;color:var(--blue)}.note{margin-top:14px;padding:13px 15px;border:1px solid #dbe5ff;background:#f8faff;border-radius:13px;font-size:11px;line-height:1.6;color:#475467}
@media(max-width:850px){.settings-shell{grid-template-columns:1fr}.settings-menu{position:static;display:grid;grid-template-columns:repeat(2,1fr);gap:3px}.menu-title{grid-column:1/-1}.menu-group{margin:0}.menu-label{display:none}.settings-menu a{margin:1px}}@media(max-width:600px){.settings-menu{grid-template-columns:1fr}.cards,.quick{grid-template-columns:1fr}.hero{padding:23px 18px;border-radius:18px}.hero h1{font-size:26px}.wrap{padding:18px 12px!important}}
</style></head>
<body><div class="top"><strong>SkyNoc <span style="opacity:.55">/</span> Admin</strong><span><?=e($u['name'])?> · <a href="/admin">Dashboard</a> · <a href="/logout">Logout</a></span></div>
<div class="wrap"><div class="settings-shell">
<aside class="settings-menu"><div class="menu-title">Settings Menu</div>
<div class="menu-group"><div class="menu-label">Payments</div><a class="active" href="/admin/settings"><span class="mi">⚙</span>Overview</a><a href="/admin/settings/payments"><span class="mi">💳</span>Payment Methods</a><a href="/admin/settings/binance"><span class="mi">₿</span>Binance / Crypto</a></div>
<div class="menu-group"><div class="menu-label">Notifications</div><a href="/admin/settings/telegram"><span class="mi">✈</span>Telegram</a><a href="/admin/settings/telegram/message"><span class="mi">✉</span>Telegram Message</a><a href="/admin/settings/discord"><span class="mi">◉</span>Discord</a><a href="/admin/settings/smtp"><span class="mi">✉</span>SMTP / Email</a></div>
<div class="menu-group"><div class="menu-label">License Operations</div><a href="/admin/license-add"><span class="mi">＋</span>Add License</a><a href="/admin/license-transfer"><span class="mi">↔</span>Transfer License</a><a href="/admin/order-fulfill"><span class="mi">📦</span>Order Fulfillment</a><a href="/admin/renew"><span class="mi">↻</span>Renew License</a></div>
<div class="menu-group"><div class="menu-label">Platform</div><a href="/admin/reseller-levels"><span class="mi">🏆</span>Reseller Levels</a><a href="/admin/reseller-funds"><span class="mi">💰</span>Manual Funds</a><a href="/admin/hostname"><span class="mi">🌐</span>Hostname Product</a><a href="/security"><span class="mi">🔐</span>Security</a></div></aside>
<main class="content"><div class="hero"><span class="eyebrow">⚙ ADMIN CONTROL CENTER</span><h1>Settings & Quick Access</h1><p>All platform settings and recently added management tools are available from one responsive control center.</p></div>
<div class="section-title"><h3>Configuration</h3><span>Choose a settings area</span></div><div class="cards">
<a class="setting-card" href="/admin/settings/payments"><div class="icon">💳</div><div><h2>Payment Methods</h2><p>Deposit methods, minimum deposit, instructions, sort order and USDT/BSC verification.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/admin/settings/telegram"><div class="icon">✈️</div><div><h2>Telegram</h2><p>Unified Telegram bot, admin notifications and client support configuration.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/admin/settings/smtp"><div class="icon">✉️</div><div><h2>SMTP / Email</h2><p>SMTP host, port, encryption, sender identity and delivery test.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/admin/settings/discord"><div class="icon">◉</div><div><h2>Discord</h2><p>Platform Discord webhook and notification channel configuration.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/admin/settings/binance"><div class="icon">₿</div><div><h2>Binance / Crypto</h2><p>Existing Binance and crypto payment integration configuration.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/admin/reseller-levels"><div class="icon">🏆</div><div><h2>Reseller Levels</h2><p>License-count levels, pricing discounts and commercial rules.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/admin/reseller-funds"><div class="icon">💰</div><div><h2>Manual Reseller Funds</h2><p>Directly credit reseller wallets with audit and transaction records.</p><div class="arrow">Open funding tool →</div></div></a>
<a class="setting-card" href="/admin/hostname"><div class="icon">🌐</div><div><h2>Hostname Product</h2><p>Hostname product pricing, configuration and inventory.</p><div class="arrow">Open settings →</div></div></a>
<a class="setting-card" href="/security"><div class="icon">🔐</div><div><h2>Security</h2><p>Administrator authentication and account security controls.</p><div class="arrow">Open settings →</div></div></a></div>
<div class="section-title"><h3>Admin Tools</h3><span>Quick access</span></div><div class="quick"><a href="/admin">← Admin Dashboard</a><a href="/admin/license-add">➕ Add License</a><a href="/admin/license-transfer">↔ License Transfer</a><a href="/admin/reseller-funds">💰 Manual Funds</a><a href="/admin/coupons">🎟 Coupons</a><a href="/admin/order-fulfill">📦 Order Fulfillment</a><a href="/admin/renew">🔄 Renewals</a><a href="/admin/reports">📊 Reports</a><a href="/api-docs">🔌 API Docs</a></div>
<div class="note">New license management pages are linked here so staff do not need to remember direct URLs. Existing payment, Telegram, Discord, SMTP, reseller and hostname settings remain available.</div></main></div></div></body></html>