<?php require __DIR__ . '/../app/bootstrap.php'; $u=require_auth(); $counts=[]; foreach(['licenses','resellers','reissue_requests'] as $t){$counts[$t]=(int)$db->query("SELECT COUNT(*) FROM {$t}")->fetchColumn();} ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SkyNoc Dashboard</title><style>
:root{--bg:#f5f7fb;--panel:#fff;--ink:#172033;--muted:#64748b;--line:#e7ebf2;--brand:#2563eb;--dark:#111827;--shadow:0 10px 30px rgba(15,23,42,.07)}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--ink);line-height:1.5}
.nav{position:sticky;top:0;z-index:20;background:rgba(15,23,42,.97);color:#fff;padding:13px 24px;display:flex;justify-content:space-between;align-items:center;gap:18px;border-bottom:1px solid rgba(255,255,255,.08);box-shadow:0 5px 18px rgba(15,23,42,.12)}
.brand{display:flex;align-items:center;gap:10px;font-size:18px;font-weight:800;white-space:nowrap}.logo{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(135deg,#3b82f6,#6366f1)}
.links{display:flex;align-items:center;gap:5px;flex-wrap:wrap;justify-content:flex-end}.links a{color:#dbeafe;text-decoration:none;padding:8px 10px;border-radius:9px;font-size:13px;font-weight:650}.links a:hover{background:rgba(255,255,255,.1);color:#fff}.user{font-size:12px;color:#cbd5e1;padding:0 6px}
.wrap{max-width:1480px;margin:auto;padding:30px 22px 55px}.head{margin-bottom:22px}.eyebrow{margin:0 0 6px;color:#64748b;font-size:14px}.head h1{margin:0;font-size:31px;letter-spacing:-.03em}.head p{margin:6px 0 0;color:var(--muted);font-size:14px}
.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.card{background:var(--panel);padding:22px;border-radius:16px;border:1px solid var(--line);box-shadow:var(--shadow)}.label{font-size:12px;color:var(--muted);font-weight:750;text-transform:uppercase;letter-spacing:.05em}.num{font-size:34px;font-weight:850;margin-top:7px;letter-spacing:-.03em}.hint{font-size:12px;color:var(--muted);margin-top:2px}
.actions{margin-top:18px}.actions h3{margin:0 0 15px;font-size:17px}.action-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.btn{display:flex;align-items:center;justify-content:center;min-height:46px;padding:11px 14px;border-radius:10px;background:var(--dark);color:#fff;text-decoration:none;font-weight:700;font-size:13px}.btn.primary{background:var(--brand)}
.footer-note{margin-top:20px;color:#94a3b8;font-size:12px}
@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.action-grid{grid-template-columns:1fr 1fr}.nav{align-items:flex-start}.links{justify-content:flex-start}}
@media(max-width:650px){.nav{padding:11px 12px;flex-direction:column;align-items:stretch}.links{width:100%;overflow-x:auto;flex-wrap:nowrap;justify-content:flex-start}.links a{white-space:nowrap;font-size:12px;padding:7px 9px}.user{white-space:nowrap}.wrap{padding:20px 11px 40px}.head h1{font-size:26px}.grid{grid-template-columns:1fr 1fr;gap:10px}.card{padding:15px}.num{font-size:25px}.action-grid{grid-template-columns:1fr}.btn{min-height:44px}}
</style></head><body>
<nav class="nav"><div class="brand"><span class="logo">S</span><span>SkyNoc</span></div><div class="links"><span class="user"><?=e($u['name'])?> · <?=e($u['role'])?></span><a href="/dashboard">Dashboard</a><a href="/admin">Admin</a><a href="/admin/reseller-levels">Levels</a><a href="/admin/settings">Settings</a><a href="/admin/reports">Reports</a><a href="/admin/coupons">Coupons</a><a href="/api-docs">API Docs</a><a href="/logout">Logout</a></div></nav>
<main class="wrap"><header class="head"><p class="eyebrow">Welcome back</p><h1>SkyNoc Dashboard</h1><p>Overview of your license reseller platform and management tools.</p></header>
<section class="grid"><div class="card"><div class="label">Licenses</div><div class="num"><?=$counts['licenses']?></div><div class="hint">Total license records</div></div><div class="card"><div class="label">Resellers</div><div class="num"><?=$counts['resellers']?></div><div class="hint">Registered reseller accounts</div></div><div class="card"><div class="label">Reissue Requests</div><div class="num"><?=$counts['reissue_requests']?></div><div class="hint">License reissue records</div></div></section>
<section class="card actions"><h3>Quick actions</h3><div class="action-grid"><a class="btn primary" href="/admin">Open Admin Panel</a><a class="btn" href="/admin/settings">Platform Settings</a><a class="btn" href="/admin/reports">View Reports</a><a class="btn" href="/api-docs">API Documentation</a></div></section>
<div class="footer-note">SkyNoc License Reseller Platform · <?=date('Y')?></div></main></body></html>