<?php
require __DIR__ . '/../app/bootstrap.php';

if (current_user()) {
    $u = current_user();
    redirect($u['role'] === 'reseller' ? '/reseller' : '/dashboard');
}
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="SkyNoc — WHMCS license sales, reseller access and license management.">
<meta name="theme-color" content="#07111f">
<title>SkyNoc — WHMCS Licenses & Reseller Platform</title>
<style>
:root{--bg:#07111f;--bg2:#0b1930;--panel:#0e2038;--blue:#4f8cff;--blue2:#2f6ff0;--cyan:#65d9ff;--green:#45d39b;--text:#f5f8ff;--muted:#9fb0c8;--ink:#102039;--line:#dfe7f2;--soft:#f6f9fd;--white:#fff;--shadow:0 24px 80px rgba(5,18,38,.18)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);line-height:1.55;background:#fff}a{text-decoration:none;color:inherit}.container{width:min(1180px,92%);margin:auto}
.top{background:#050c17;color:#9fb0c8;font-size:12px;border-bottom:1px solid rgba(255,255,255,.06)}.topin{min-height:36px;display:flex;align-items:center;justify-content:space-between;gap:20px}.top strong{color:#fff}.top span:last-child{color:#7890ad}
nav{position:sticky;top:0;z-index:100;background:rgba(7,17,31,.88);backdrop-filter:blur(16px);border-bottom:1px solid rgba(255,255,255,.08)}.navin{height:72px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:11px;color:#fff;font-weight:900;font-size:21px;letter-spacing:-.7px}.brandmark{width:36px;height:36px;border-radius:11px;background:linear-gradient(135deg,var(--blue),var(--cyan));display:grid;place-items:center;color:#06101f;font-size:13px;font-weight:950;box-shadow:0 8px 25px rgba(79,140,255,.28)}.brand small{display:block;color:#7890ad;font-size:8px;letter-spacing:1px;margin-top:-1px}.links{display:flex;align-items:center;gap:25px;color:#b8c6da;font-size:13px;font-weight:750}.links a:hover{color:#fff}.login{border:1px solid rgba(255,255,255,.15);padding:9px 14px;border-radius:9px}.get{padding:10px 16px;border-radius:9px;background:linear-gradient(135deg,var(--blue),var(--blue2));color:#fff!important;box-shadow:0 8px 24px rgba(47,111,240,.25)}
.hero{position:relative;overflow:hidden;background:radial-gradient(circle at 78% 25%,rgba(79,140,255,.2),transparent 28%),radial-gradient(circle at 15% 0%,rgba(101,217,255,.08),transparent 30%),linear-gradient(135deg,var(--bg),var(--bg2));color:#fff;padding:86px 0 92px}.hero:before{content:"";position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:44px 44px;mask-image:linear-gradient(to bottom,black,transparent 80%);pointer-events:none}.hero-grid{position:relative;display:grid;grid-template-columns:1.03fr .97fr;gap:65px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;border:1px solid rgba(101,217,255,.2);background:rgba(101,217,255,.07);color:#9ce7ff;border-radius:99px;padding:7px 11px;font-size:10px;font-weight:900;letter-spacing:.8px;text-transform:uppercase}.dot{width:6px;height:6px;background:var(--green);border-radius:50%;box-shadow:0 0 0 5px rgba(69,211,155,.1)}.hero h1{font-size:clamp(43px,5.7vw,70px);line-height:1.01;letter-spacing:-3.4px;margin:19px 0 20px;max-width:720px}.hero h1 span{background:linear-gradient(90deg,#fff 0%,#86c7ff 55%,#65d9ff 100%);-webkit-background-clip:text;background-clip:text;color:transparent}.hero p{font-size:17px;color:#aabbd1;max-width:630px;margin:0 0 30px}.actions{display:flex;gap:11px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:10px;padding:13px 18px;font-size:13px;font-weight:850;border:1px solid transparent;transition:.2s ease}.btn:hover{transform:translateY(-1px)}.primary{background:linear-gradient(135deg,var(--blue),var(--blue2));color:#fff;box-shadow:0 12px 30px rgba(47,111,240,.28)}.secondary{background:rgba(255,255,255,.05);border-color:rgba(255,255,255,.14);color:#fff}.hero-trust{display:flex;flex-wrap:wrap;gap:20px;margin-top:25px;color:#9eb0c7;font-size:11px}.hero-trust span:before{content:"✓";color:var(--green);font-weight:900;margin-right:6px}
.dashboard{border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.065);border-radius:22px;padding:10px;box-shadow:0 30px 90px rgba(0,0,0,.32);transform:perspective(1200px) rotateY(-4deg)}.dash{background:#f8fbff;color:var(--ink);border-radius:15px;overflow:hidden}.dashbar{height:44px;background:#edf3fa;border-bottom:1px solid #dfe8f2;display:flex;align-items:center;justify-content:space-between;padding:0 14px}.lights{display:flex;gap:5px}.lights i{width:7px;height:7px;border-radius:50%;background:#b8c6d7}.dashbar small{color:#788aa2;font-size:9px;font-weight:800}.dashbody{padding:20px}.dashhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:17px}.dashhead b{font-size:17px}.dashhead small{display:block;color:#8a99ad;font-size:9px;margin-top:2px}.active{background:#e5f8f0;color:#17855f;padding:5px 9px;border-radius:99px;font-size:9px;font-weight:900}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.stat{background:#fff;border:1px solid #e1e9f2;border-radius:10px;padding:12px}.stat small{display:block;color:#8493a7;font-size:9px}.stat b{display:block;font-size:18px;margin-top:2px}.license-list{margin-top:11px;background:#fff;border:1px solid #e1e9f2;border-radius:10px;overflow:hidden}.license-row{display:grid;grid-template-columns:1.25fr .9fr .5fr;gap:10px;padding:12px;border-bottom:1px solid #edf1f5;font-size:10px}.license-row:last-child{border:0}.license-row small{color:#8b98aa}.ok{color:#16855e;font-weight:850}.dashfoot{margin-top:11px;padding:11px 12px;border-radius:9px;background:#eef5ff;color:#57708f;font-size:10px}
.strip{background:#fff;border-bottom:1px solid var(--line)}.stripin{display:grid;grid-template-columns:repeat(3,1fr);gap:0}.stripitem{padding:21px 24px;border-right:1px solid var(--line);display:flex;align-items:center;gap:12px}.stripitem:last-child{border:0}.stripicon{width:35px;height:35px;border-radius:10px;background:#edf5ff;color:var(--blue2);display:grid;place-items:center;font-weight:950}.stripitem b{display:block;font-size:13px}.stripitem small{color:#74849a;font-size:10px}
.section{padding:84px 0}.soft{background:var(--soft)}.center{text-align:center}.label{color:#3975d8;font-size:10px;font-weight:950;letter-spacing:1.1px;text-transform:uppercase}.head{max-width:700px;margin:0 auto 38px}.head h2{font-size:37px;line-height:1.12;letter-spacing:-1.6px;margin:8px 0 11px;color:#102039}.head p{margin:0;color:#718198;font-size:14px}.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:17px}.plan{position:relative;background:#fff;border:1px solid var(--line);border-radius:17px;padding:27px;box-shadow:0 8px 30px rgba(18,45,78,.045)}.plan.featured{border:2px solid #4f8cff;padding:26px;box-shadow:0 18px 50px rgba(47,111,240,.13)}.badge{position:absolute;top:16px;right:16px;border-radius:99px;padding:5px 8px;background:#eaf2ff;color:#2567d6;font-size:8px;font-weight:950}.plan h3{font-size:20px;margin:0 0 5px}.plan p{font-size:12px;color:#718198;min-height:38px;margin:0}.price{font-size:32px;font-weight:950;letter-spacing:-1.5px;margin:19px 0 1px}.price small{font-size:11px;color:#8795a8;font-weight:700;letter-spacing:0}.plan ul{list-style:none;padding:0;margin:18px 0 21px}.plan li{font-size:12px;color:#52637a;padding:8px 0;border-top:1px solid #edf1f5}.plan li:before{content:"✓";color:#18a873;font-weight:950;margin-right:8px}.full{width:100%}.plan-note{text-align:center;color:#8391a4;font-size:10px;margin-top:22px}
.why{display:grid;grid-template-columns:.85fr 1.15fr;gap:70px;align-items:center}.why-copy h2{font-size:39px;line-height:1.1;letter-spacing:-1.6px;margin:8px 0 14px}.why-copy p{color:#718198;font-size:14px;max-width:500px}.feature-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.feature{padding:21px;border:1px solid var(--line);border-radius:15px;background:#fff}.featureicon{width:34px;height:34px;border-radius:10px;background:#eef5ff;color:#3275dd;display:grid;place-items:center;font-weight:950;margin-bottom:13px}.feature h3{font-size:15px;margin:0 0 6px}.feature p{font-size:11px;color:#718198;margin:0}
.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.step{position:relative;background:#fff;border:1px solid var(--line);border-radius:16px;padding:25px}.stepno{width:31px;height:31px;border-radius:10px;background:#102b50;color:#83baff;display:grid;place-items:center;font-size:11px;font-weight:950;margin-bottom:17px}.step h3{font-size:16px;margin:0 0 6px}.step p{font-size:12px;color:#718198;margin:0}.step:after{content:"→";position:absolute;right:-14px;top:42%;width:27px;height:27px;border-radius:50%;background:#fff;border:1px solid var(--line);display:grid;place-items:center;color:#4b82dd;font-weight:900;z-index:2}.step:last-child:after{display:none}
.cta{position:relative;overflow:hidden;background:linear-gradient(135deg,#071426,#102b50);color:#fff;padding:76px 0}.cta:after{content:"";position:absolute;width:400px;height:400px;border-radius:50%;right:-180px;top:-190px;background:rgba(79,140,255,.18);filter:blur(8px)}.ctain{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:30px}.cta h2{font-size:35px;line-height:1.12;letter-spacing:-1.3px;margin:0 0 9px}.cta p{color:#a7bad3;font-size:13px;margin:0;max-width:650px}.ctaactions{display:flex;gap:10px;flex:none}
.faq{max-width:850px;margin:auto}.faq details{border-top:1px solid var(--line);padding:19px 2px}.faq details:last-child{border-bottom:1px solid var(--line)}.faq summary{cursor:pointer;font-size:14px;font-weight:850;list-style:none}.faq summary::-webkit-details-marker{display:none}.faq summary:after{content:"+";float:right;color:#5f7897;font-size:19px;font-weight:500}.faq details[open] summary:after{content:"−"}.faq p{font-size:12px;color:#718198;margin:9px 35px 0 0}
footer{background:#050d19;color:#8192a9;padding:38px 0 24px;font-size:11px}.foot{display:flex;justify-content:space-between;gap:25px;flex-wrap:wrap}.footbrand{color:#fff;font-weight:900;font-size:17px}.footbrand small{display:block;color:#71839b;font-size:8px;letter-spacing:1px;margin-top:1px}.footlinks{display:flex;gap:20px;flex-wrap:wrap}.footlinks a:hover{color:#fff}.legal{margin-top:26px;padding-top:17px;border-top:1px solid #18273b;color:#65768d;font-size:10px;line-height:1.7}
@media(max-width:950px){.hero-grid,.why{grid-template-columns:1fr}.dashboard{max-width:700px;margin:auto}.plans{grid-template-columns:1fr}.why{gap:35px}.ctain{display:block}.ctaactions{margin-top:22px}.links a.hide{display:none}.hero{padding-top:65px}}
@media(max-width:650px){.topin{justify-content:center}.top span:last-child{display:none}.navin{height:64px}.links{gap:6px}.links a:not(.login):not(.get){display:none}.brand{font-size:19px}.hero{padding:55px 0 65px}.hero h1{font-size:43px;letter-spacing:-2.4px}.hero p{font-size:15px}.actions .btn{width:100%}.hero-trust{gap:11px;display:grid;grid-template-columns:1fr 1fr}.dashboard{transform:none;padding:7px;border-radius:17px}.dashbody{padding:14px}.stats{grid-template-columns:1fr 1fr}.stats .stat:last-child{grid-column:1/-1}.license-row{grid-template-columns:1fr .55fr}.license-row small{display:none}.stripin{grid-template-columns:1fr}.stripitem{border-right:0;border-bottom:1px solid var(--line);padding:17px}.section{padding:65px 0}.head h2,.why-copy h2{font-size:30px}.feature-grid,.steps{grid-template-columns:1fr}.step:after{display:none}.cta h2{font-size:29px}.ctaactions{display:grid}.ctaactions .btn{width:100%}}
</style>
</head>
<body>
<div class="top"><div class="container topin"><span><strong>SkyNoc</strong> — WHMCS License Sales & Reseller Platform</span><span>Secure access • Fast support • Reseller tools</span></div></div>
<nav><div class="container navin"><a class="brand" href="/"><span class="brandmark">SN</span><span>SkyNoc<small>WHMCS LICENSES</small></span></a><div class="links"><a class="hide" href="#plans">Licenses</a><a class="hide" href="#why">Why SkyNoc</a><a class="hide" href="#faq">FAQ</a><a class="hide" href="/api-docs">API Docs</a><a class="login" href="/login">Login</a><a class="get" href="/reseller/register">Become a Reseller</a></div></div></nav>
<main>
<section class="hero"><div class="container hero-grid"><div><div class="eyebrow"><i class="dot"></i> WHMCS License Reseller Network</div><h1>Run your WHMCS business with <span>confidence.</span></h1><p>Get access to WHMCS licenses, reseller pricing and a dedicated management portal built for hosting businesses, agencies and service providers.</p><div class="actions"><a class="btn primary" href="/reseller/register">Start Reselling →</a><a class="btn secondary" href="https://www.whmcs.com/members/aff.php?aff=42837" target="_blank" rel="noopener noreferrer">Buy Direct from WHMCS ↗</a></div><div class="hero-trust"><span>Genuine licensing</span><span>Reseller pricing</span><span>Human support</span></div></div><div class="dashboard" aria-label="SkyNoc dashboard preview"><div class="dash"><div class="dashbar"><div class="lights"><i></i><i></i><i></i></div><small>app.skynoc.net / reseller</small></div><div class="dashbody"><div class="dashhead"><div><b>License overview</b><small>Reseller account</small></div><span class="active">ACCOUNT ACTIVE</span></div><div class="stats"><div class="stat"><small>Current plan</small><b>Professional</b></div><div class="stat"><small>Licenses</small><b>24</b></div><div class="stat"><small>Wallet</small><b>$248.00</b></div></div><div class="license-list"><div class="license-row"><b>billing.example.com</b><small>WHMCS License</small><span class="ok">Active</span></div><div class="license-row"><b>support.example.com</b><small>Reissue request</small><span>Review</span></div><div class="license-row"><b>portal.example.com</b><small>WHMCS License</small><span class="ok">Active</span></div></div><div class="dashfoot">Manage licenses, balance, orders and reseller activity from one secure portal.</div></div></div></div></div></section>
<section class="strip"><div class="container stripin"><div class="stripitem"><div class="stripicon">01</div><div><b>Simple reseller access</b><small>Register and manage your account online.</small></div></div><div class="stripitem"><div class="stripicon">02</div><div><b>Wallet-based ordering</b><small>Use your reseller balance for purchases.</small></div></div><div class="stripitem"><div class="stripicon">03</div><div><b>License support</b><small>Reissue requests are handled by our team.</small></div></div></div></section>
<section class="section" id="plans"><div class="container"><div class="head center"><div class="label">WHMCS License Plans</div><h2>Choose the license that fits your business</h2><p>Clear plans for growing hosting companies, agencies and WHMCS service providers.</p></div><div class="plans"><div class="plan"><h3>Plus</h3><p>For smaller businesses and new WHMCS installations.</p><div class="price">$34.95 <small>/ month</small></div><ul><li>Self-hosted WHMCS</li><li>Up to 250 active clients</li><li>Standard support</li></ul><a class="btn secondary" style="color:#102039;border-color:#d3deeb;width:100%" href="/reseller/register">Get Started</a></div><div class="plan featured"><span class="badge">MOST REQUESTED</span><h3>Professional</h3><p>For growing hosting and service businesses.</p><div class="price">$54.95 <small>/ month</small></div><ul><li>Self-hosted WHMCS</li><li>Up to 500 active clients</li><li>Standard support</li></ul><a class="btn primary full" href="/reseller/register">Get Started →</a></div><div class="plan"><h3>Business</h3><p>For established operations with higher client limits.</p><div class="price">From $84.95 <small>/ month</small></div><ul><li>Self-hosted WHMCS</li><li>Higher client capacity</li><li>Priority account support</li></ul><a class="btn secondary" style="color:#102039;border-color:#d3deeb;width:100%" href="/reseller/register">Get Started</a></div></div><div class="plan-note">Pricing shown is a reference. Final availability and SkyNoc reseller pricing are confirmed in your account.</div></div></section>
<section class="section soft" id="why"><div class="container why"><div class="why-copy"><div class="label">Why SkyNoc</div><h2>Everything you need to sell and manage licenses.</h2><p>SkyNoc is designed around a simple reseller workflow: fund your wallet, purchase licenses, manage your orders and contact support when you need help.</p><a class="btn primary" href="/reseller/register">Create Reseller Account →</a></div><div class="feature-grid"><div class="feature"><div class="featureicon">$</div><h3>Reseller wallet</h3><p>Keep your balance ready for license purchases and account activity.</p></div><div class="feature"><div class="featureicon">↗</div><h3>License reissue</h3><p>Submit reissue requests from the reseller workflow and receive status updates.</p></div><div class="feature"><div class="featureicon">API</div><h3>API ready</h3><p>Connect your own billing workflow using the SkyNoc API and documentation.</p></div><div class="feature"><div class="featureicon">✓</div><h3>Human support</h3><p>Get direct help for licensing and reseller account issues.</p></div></div></div></section>
<section class="section"><div class="container"><div class="head center"><div class="label">How it works</div><h2>Start selling in three simple steps</h2><p>No complicated onboarding. Create your reseller account and use the portal to manage your business.</p></div><div class="steps"><div class="step"><div class="stepno">01</div><h3>Create your account</h3><p>Register as a SkyNoc reseller and complete the account setup.</p></div><div class="step"><div class="stepno">02</div><h3>Fund your wallet</h3><p>Add balance using the available payment method shown in your account.</p></div><div class="step"><div class="stepno">03</div><h3>Buy & manage licenses</h3><p>Place license orders, track activity and request support from one portal.</p></div></div></div></section>
<section class="cta"><div class="container ctain"><div><h2>Ready to build your WHMCS business?</h2><p>Create your SkyNoc reseller account and get access to the tools you need to manage your license sales.</p></div><div class="ctaactions"><a class="btn primary" href="/reseller/register">Become a Reseller →</a><a class="btn secondary" href="/login">Already a member? Login</a></div></div></section>
<section class="section" id="faq"><div class="container"><div class="head center"><div class="label">FAQ</div><h2>Questions, answered.</h2><p>Quick answers before you create your reseller account.</p></div><div class="faq"><details><summary>Who can become a SkyNoc reseller?</summary><p>Hosting companies, agencies, freelancers and service providers can register for a reseller account and use the available SkyNoc license services.</p></details><details><summary>How do reseller license purchases work?</summary><p>Resellers maintain a wallet balance and use that balance for eligible license orders. Your portal shows the relevant order and license status.</p></details><details><summary>Can I integrate SkyNoc with my own billing system?</summary><p>Yes. SkyNoc provides an API area for supported reseller workflows. See the API documentation after reviewing your account access.</p></details><details><summary>How do I get support for a license?</summary><p>Use the support/reissue workflow in your account. Our team can review eligible license requests and provide the next steps.</p></details></div></div></section>
</main>
<footer><div class="container"><div class="foot"><div><div class="footbrand">SkyNoc<small>WHMCS LICENSES & RESELLER PLATFORM</small></div></div><div class="footlinks"><a href="#plans">Licenses</a><a href="/reseller/register">Reseller</a><a href="/login">Login</a><a href="/api-docs">API Docs</a><a href="#faq">FAQ</a></div></div><div class="legal">© <?php echo date('Y'); ?> SkyNoc. All rights reserved. WHMCS is a trademark of WHMCS SMARTERS. SkyNoc is an independent license reseller and is not WHMCS itself.</div></div></footer>
</body>
</html>
