<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
$u=require_auth();
$id=(int)($_GET['id']??0);

$invoiceSettings=['company_name'=>'SkyNoc','tagline'=>'WHMCS License Services','logo_url'=>null,'address'=>null,'email'=>null,'phone'=>null,'website'=>null,'currency'=>'USD','invoice_prefix'=>'SN-','footer_text'=>'Thank you for using SkyNoc.'];
try {
    $db->exec("CREATE TABLE IF NOT EXISTS invoice_settings (id TINYINT UNSIGNED PRIMARY KEY,company_name VARCHAR(160) NOT NULL DEFAULT 'SkyNoc',tagline VARCHAR(255) NULL,logo_url VARCHAR(500) NULL,address TEXT NULL,email VARCHAR(190) NULL,phone VARCHAR(60) NULL,website VARCHAR(500) NULL,currency VARCHAR(10) NOT NULL DEFAULT 'USD',invoice_prefix VARCHAR(30) NOT NULL DEFAULT 'SN-',footer_text TEXT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $s=$db->query('SELECT * FROM invoice_settings WHERE id=1 LIMIT 1');
    $cfg=$s->fetch();
    if ($cfg) $invoiceSettings=array_merge($invoiceSettings,$cfg);
} catch (Throwable $e) { /* Keep invoice rendering available if settings storage is unavailable. */ }

$s=$db->prepare('SELECT i.*,r.name reseller_name,r.email reseller_email,o.domain,p.name package_name FROM invoices i JOIN resellers r ON r.id=i.reseller_id LEFT JOIN orders o ON o.id=i.order_id LEFT JOIN packages p ON p.id=o.package_id WHERE i.id=? LIMIT 1');$s->execute([$id]);$i=$s->fetch();
if(!$i) {http_response_code(404);exit('Invoice not found.');}
if($u['role']==='reseller'){$q=$db->prepare('SELECT id FROM resellers WHERE user_id=?');$q->execute([$u['id']]);if((int)$q->fetchColumn()!==(int)$i['reseller_id']){http_response_code(403);exit('Forbidden');}}
$s=$db->prepare('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id');$s->execute([$id]);$items=$s->fetchAll();
$currency=e((string)($invoiceSettings['currency']??'USD'));
$money=function(float $amount) use ($currency): string { return $currency.' '.number_format($amount,2); };
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($i['invoice_number'])?> — <?=e((string)$invoiceSettings['company_name'])?></title><style>body{margin:0;background:#f3f4f6;font-family:Inter,system-ui,sans-serif;color:#111827}.sheet{max-width:800px;margin:30px auto;background:#fff;padding:35px;border-radius:16px;box-shadow:0 12px 35px rgba(15,23,42,.08)}.head{display:flex;justify-content:space-between;gap:20px}.brand-logo{max-width:180px;max-height:60px;object-fit:contain;margin-bottom:8px}.brand h1{margin:0 0 3px}.muted{color:#64748b}.small{font-size:12px;color:#64748b;line-height:1.55}table{width:100%;border-collapse:collapse;margin-top:30px}td,th{padding:12px;border-bottom:1px solid #e5e7eb;text-align:left}.total{text-align:right;font-size:20px;font-weight:800;line-height:1.8;margin-top:20px}.paid{color:#166534;font-weight:800}.footer{margin-top:28px;padding-top:16px;border-top:1px solid #e5e7eb;color:#64748b;font-size:12px;line-height:1.6}@media(max-width:600px){.sheet{margin:0;padding:22px;border-radius:0}.head{flex-direction:column}.total{text-align:left}}
</style></head><body><main class="sheet"><div class="head"><div class="brand"><?php if(!empty($invoiceSettings['logo_url'])):?><img class="brand-logo" src="<?=e((string)$invoiceSettings['logo_url'])?>" alt="<?=e((string)$invoiceSettings['company_name'])?>"><br><?php endif;?><h1><?=e((string)$invoiceSettings['company_name'])?></h1><div class="muted"><?=e((string)($invoiceSettings['tagline']??''))?></div><?php if(!empty($invoiceSettings['address'])):?><div class="small"><?=nl2br(e((string)$invoiceSettings['address']))?></div><?php endif;?></div><div><b><?=e($i['invoice_number'])?></b><br><?=e($i['created_at'])?><br><span class="paid"><?=e(strtoupper($i['status']))?></span></div></div><hr><p><b>Bill To:</b><br><?=e($i['reseller_name'])?><br><?=e($i['reseller_email'])?></p><?php if($invoiceSettings['email']||$invoiceSettings['phone']||$invoiceSettings['website']):?><p class="small"><?=e((string)($invoiceSettings['email']??''))?><?=($invoiceSettings['phone']??'')?' · '.e((string)$invoiceSettings['phone']):''?><?=($invoiceSettings['website']??'')?' · '.e((string)$invoiceSettings['website']):''?></p><?php endif;?><table><tr><th>Description</th><th>Qty</th><th>Amount</th></tr><?php foreach($items as $x):?><tr><td><?=e($x['description'])?><?=($i['domain']?'<br><small class="muted">'.e($i['domain']).'</small>':'')?></td><td><?=e((string)$x['quantity'])?></td><td><?=$money((float)$x['amount'])?></td></tr><?php endforeach;?></table><div class="total">Subtotal: <?=$money((float)$i['subtotal'])?><br>Discount: -<?=$money((float)$i['discount'])?><br>Total: <?=$money((float)$i['total'])?></div><div class="footer"><?=nl2br(e((string)($invoiceSettings['footer_text']??'Thank you for using SkyNoc.')))?></div></main></body></html>