<?php
require __DIR__ . '/../app/bootstrap.php';
$u=require_role(['owner','admin','manager']);
$days=max(1,min(365,(int)($_GET['days']??30)));
$s=$db->prepare("SELECT COUNT(*) orders_count,COALESCE(SUM(amount),0) revenue,COALESCE(SUM(CASE WHEN status='refunded' THEN amount ELSE 0 END),0) refunded FROM orders WHERE created_at>=DATE_SUB(NOW(),INTERVAL ? DAY)");
$s->execute([$days]); $summary=$s->fetch()?:[];
$stats=$db->query("SELECT DATE(created_at) day,COUNT(*) orders_count,COALESCE(SUM(amount),0) revenue FROM orders GROUP BY DATE(created_at) ORDER BY day DESC LIMIT 31")->fetchAll();
$licenses=(int)$db->query("SELECT COUNT(*) FROM licenses WHERE status='active'")->fetchColumn();
$pending=(int)$db->query("SELECT COUNT(*) FROM reissue_requests WHERE status IN ('pending','review','manual_reissue')")->fetchColumn();
$deposits=(float)$db->query("SELECT COALESCE(SUM(amount),0) FROM deposit_requests WHERE status='approved' AND created_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)")->fetchColumn();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reports — SkyNoc</title><link rel="stylesheet" href="/admin-page-ui.css"><style>*{box-sizing:border-box}body{margin:0;background:#f6f8fb;color:#0f172a;font-family:Inter,system-ui,sans-serif}.nav{background:#111827;color:#fff;padding:15px 5%;display:flex;justify-content:space-between}.nav a{color:#fff}.wrap{max-width:1200px;margin:24px auto;padding:0 14px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:18px}.num{font-size:28px;font-weight:800;margin-top:8px}.muted{color:#64748b}.table{overflow:auto;margin-top:18px}table{width:100%;border-collapse:collapse;background:#fff}th,td{padding:11px;border-bottom:1px solid #eef2f7;text-align:left}select,button{padding:9px;border:1px solid #dbe2ea;border-radius:9px}button{background:#111827;color:#fff}@media(max-width:700px){.nav{flex-direction:column;gap:8px}.table{overflow-x:auto}table{min-width:650px}}</style></head><body><div class="nav"><b>SkyNoc Reports</b><span><?=e($u['name'])?> · <a href="/admin">Admin</a> · <a href="/logout">Logout</a></span></div><main class="wrap"><h1>Business Reports</h1><p class="muted">Monitor sales, revenue, refunds, active licenses, deposits and open reissues.</p><form><select name="days"><option value="7" <?=$days===7?'selected':''?>>7 days</option><option value="30" <?=$days===30?'selected':''?>>30 days</option><option value="90" <?=$days===90?'selected':''?>>90 days</option><option value="365" <?=$days===365?'selected':''?>>365 days</option></select> <button>Apply</button></form><div class="grid"><div class="card">Orders<div class="num"><?=number_format((int)$summary['orders_count'])?></div></div><div class="card">Revenue<div class="num">$<?=number_format((float)$summary['revenue'],2)?></div></div><div class="card">Refunded<div class="num">$<?=number_format((float)$summary['refunded'],2)?></div></div><div class="card">Active Licenses<div class="num"><?=$licenses?></div></div><div class="card">Approved Deposits (30d)<div class="num">$<?=number_format($deposits,2)?></div></div><div class="card">Open Reissues<div class="num"><?=$pending?></div></div></div><div class="table"><table><tr><th>Date</th><th>Orders</th><th>Revenue</th></tr><?php foreach($stats as $row):?><tr><td><?=e($row['day'])?></td><td><?=number_format((int)$row['orders_count'])?></td><td>$<?=number_format((float)$row['revenue'],2)?></td></tr><?php endforeach;?></table></div><div class="page-footer">SkyNoc Admin · <a href="/admin">Back to Admin</a> · <a href="mailto:support@skynoc.net">support@skynoc.net</a></div></main></body></html>