<?php
require __DIR__ . '/../app/bootstrap.php';
$u = require_role(['reseller']);
$s = $db->prepare('SELECT id FROM resellers WHERE user_id=? LIMIT 1');
$s->execute([$u['id']]);
$r = $s->fetch();
if (!$r) exit('Reseller profile not found.');
$rid=(int)$r['id'];
$wallet=reseller_wallet($rid);
$level=reseller_level($rid);
$discount=reseller_level_discount((int)$level['assigned_level']);
$s=$db->prepare('SELECT COUNT(*) FROM licenses WHERE reseller_id=? AND status="active"');
$s->execute([$rid]);
$activeLicenses=(int)$s->fetchColumn();
$s=$db->prepare('SELECT COUNT(*) FROM notifications WHERE reseller_id=? AND read_at IS NULL');
$s->execute([$rid]);
$unread=(int)$s->fetchColumn();
$levelName=(string)($level['name'] ?? ('Level '.(int)$level['assigned_level']));
$impersonating = !empty($_SESSION['impersonating_admin_id']);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SkyNoc Reseller Quick Links</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f8fb;color:#101828;font-family:Inter,system-ui,sans-serif}.wrap{max-width:1200px;margin:auto;padding:28px 18px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.brand{font-weight:900;font-size:20px}.brand span{color:#465fff}.return{display:inline-block;background:#465fff;color:#fff;padding:8px 11px;border-radius:9px;font-weight:800;font-size:12px}.links{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.link{display:block;background:#fff;border:1px solid #e4e7ec;border-radius:14px;padding:20px;text-decoration:none;color:#101828;box-shadow:0 8px 25px #1018280a;transition:.16s}.link:hover{transform:translateY(-2px);border-color:#c7d2fe;box-shadow:0 12px 30px #10182812}.link b{display:block;font-size:16px;margin-bottom:7px}.link small{color:#667085;line-height:1.5}.level{background:linear-gradient(135deg,#111827,#293a70);color:#fff;border-radius:16px;padding:22px;margin-bottom:20px}.level small{color:#b9c2d4}.level strong{display:block;font-size:26px;margin:5px 0}.meta{display:flex;gap:24px;color:#d7deea;flex-wrap:wrap}.badge{display:inline-block;background:#eef2ff;color:#465fff;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:800}.section{margin:22px 0 10px;font-size:13px;font-weight:900;color:#667085;text-transform:uppercase;letter-spacing:.06em}@media(max-width:850px){.links{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.links{grid-template-columns:1fr}.top{align-items:flex-start;gap:12px;flex-direction:column}.wrap{padding:20px 12px}.meta{gap:10px;flex-direction:column}}
</style></head><body><main class="wrap"><div class="top"><div class="brand"><span>SkyNoc</span> Reseller</div><div><?php if($impersonating): ?><a class="return" href="/logout">← Return to Admin</a> · <?php endif; ?><a href="/reseller">Dashboard</a> · <a href="/logout">Logout</a></div></div><section class="level"><?php if($impersonating): ?><div style="background:#fff3cd;color:#7a4b00;border-radius:10px;padding:9px 11px;margin-bottom:13px;font-size:12px;font-weight:800">Admin support session: you are viewing this reseller account.</div><?php endif; ?><small>YOUR RESELLER LEVEL</small><strong><?=e($levelName)?></strong><div class="meta"><span><?=number_format($activeLicenses)?> active licenses</span><span><?=number_format($discount,2)?>% discount</span><span>$<?=number_format($wallet,2)?> wallet</span></div></section><div class="section">Workspace</div><div class="links"><a class="link" href="/reseller"><b>Dashboard</b><small>Reseller overview and package ordering</small></a><a class="link" href="/reseller/manage#licenses"><b>My Licenses</b><small>View and manage active licenses</small></a><a class="link" href="/reseller/transfer"><b>Transfer License</b><small>Transfer an eligible license to another reseller</small></a><a class="link" href="/reseller/manage#orders"><b>My Orders</b><small>Orders, fulfillment and invoices</small></a><a class="link" href="/reseller/notifications"><b>Notifications<?= $unread ? ' ('.$unread.')' : '' ?></b><small>Telegram, Discord and email alerts</small></a><a class="link" href="/reseller/manage#deposits"><b>Wallet & Deposits</b><small>Add funds and view deposit history</small></a><a class="link" href="/reseller/manage#api"><b>API Access</b><small>API keys and integration tools</small></a><a class="link" href="/api-docs"><b>API Documentation</b><small>WHMCS and reseller API reference</small></a><a class="link" href="/reseller/manage#support"><b>Support</b><small>Tickets and reissue requests</small></a><a class="link" href="/reseller/levels"><b>Reseller Levels</b><small>Levels, discounts and profit</small></a><a class="link" href="/reseller/white-label"><b>White-label</b><small>Branding settings</small></a><a class="link" href="/security"><b>Security</b><small>Account security and 2FA</small></a></div></main></body></html>
