<?php
require __DIR__ . '/../app/bootstrap.php';
$u=require_role(['reseller']);
$s=$db->prepare('SELECT * FROM resellers WHERE user_id=? LIMIT 1');$s->execute([$u['id']]);$r=$s->fetch();if(!$r)exit('Reseller profile not found.');
$level=reseller_level((int)$r['id']);$thresholds=reseller_level_thresholds();
$base=14.50;$q=$db->query('SELECT price FROM packages WHERE active=1 ORDER BY sort_order,id LIMIT 1');if($q){$v=$q->fetchColumn();if($v!==false&&(float)$v>0)$base=(float)$v;}$retail=17.22;$rows=[];foreach($thresholds as $n=>$range){$d=reseller_level_discount($n);$p=reseller_package_price($base,$n);$rows[$n]=[$d,$p,round($retail-$p,2)];}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reseller Levels — SkyNoc</title><style>
*{box-sizing:border-box}body{margin:0;background:#050505;color:#f5f5f5;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.nav{height:64px;border-bottom:1px solid #202020;display:flex;align-items:center;justify-content:space-between;padding:0 5%}.brand{font-weight:900}.brand span{color:#777;font-size:10px;margin-left:5px}.links{display:flex;gap:18px;color:#999;font-size:12px;font-weight:700}.links a{color:inherit;text-decoration:none}.links a:hover{color:#fff}.wrap{width:min(1120px,92%);margin:auto;padding:46px 0}.hero{margin-bottom:28px}.eyebrow{font-size:11px;color:#777;text-transform:uppercase;letter-spacing:.16em;font-weight:900}.hero h1{font-size:clamp(30px,4vw,48px);line-height:1.05;letter-spacing:-1.8px;margin:9px 0}.hero p{color:#999;font-size:14px;margin:0;max-width:760px}.panel{background:#090909;border:1px solid #202020;border-radius:13px;overflow:hidden}.scroll{overflow-x:auto}table{width:100%;min-width:720px;border-collapse:collapse}th,td{padding:15px 16px;border-bottom:1px solid #1d1d1d}th{font-size:11px;color:#c9c9c9;text-align:left;background:#070707}td{font-size:13px}.center{text-align:center}.right{text-align:right;font-variant-numeric:tabular-nums}.level{font-weight:850}.discount,.profit{font-weight:850}.note{padding:15px 17px;border-top:1px solid #202020;color:#777;font-size:11px;display:flex;justify-content:space-between;gap:20px}.note b{color:#aaa}.footer{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;color:#666;font-size:11px;margin-top:20px}.footer a{color:#aaa;text-decoration:none}@media(max-width:760px){.links a:nth-child(2){display:none}.wrap{padding:30px 0}.hero h1{font-size:32px}.note{display:block}.note span{display:block;margin:4px 0}}
</style></head><body>
<nav class="nav"><a class="brand" href="/" style="color:#fff;text-decoration:none">SkyNoc <span>RESELLER</span></a><div class="links"><a href="/reseller">Dashboard</a><a href="/reseller/manage">My Licenses</a><a href="/logout">Logout</a></div></nav>
<main class="wrap"><section class="hero"><div class="eyebrow">SkyNoc reseller program</div><h1>Reseller Levels &amp; Discounts</h1><p>Higher active-license levels unlock better discounts and give resellers more room for margin.</p></section>
<section class="panel"><div class="scroll"><table><thead><tr><th>Level</th><th class="center">Active Licenses</th><th class="center">Discount</th><th class="right">Selling Price</th><th class="right">Profit/License</th></tr></thead><tbody><?php foreach($thresholds as $n=>$range):?><tr><td class="level"><?=e('Level '.$n.' – '.$range['name'])?></td><td class="center"><?=number_format($range['min'])?><?= $n===5?'+':'–'.number_format($range['max'])?></td><td class="center discount"><?=number_format($rows[$n][0],0)?>%</td><td class="right">$<?=number_format($rows[$n][1],2)?></td><td class="right profit">$<?=number_format($rows[$n][2],2)?></td></tr><?php endforeach;?></tbody></table></div><div class="note"><span>Reference package cost: <b>$<?=number_format($base,2)?></b> · Reference reseller selling price: <b>$<?=number_format($retail,2)?></b></span><span>Actual order pricing follows your active package and assigned level.</span></div></section>
<div class="footer"><span>SkyNoc Reseller Program</span><span><a href="mailto:support@skynoc.net">support@skynoc.net</a> · <a href="/reseller">Back to Dashboard</a></span></div></main></body></html>
