<?php
require __DIR__ . '/../app/bootstrap.php';
$u=require_auth(); $msg=null;$error=null;
function sn_base32_decode(string $s): string { $alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$s=strtoupper(preg_replace('/[^A-Z2-7]/','',$s));$bits='';foreach(str_split($s) as $c){$p=strpos($alphabet,$c);if($p!==false)$bits.=str_pad(decbin($p),5,'0',STR_PAD_LEFT);} $out='';for($i=0;$i+7<strlen($bits);$i+=8)$out.=chr(bindec(substr($bits,$i,8)));return $out;}
function sn_totp(string $secret,int $counter): string {$key=sn_base32_decode($secret);$bin=pack('N*',0).pack('N*',$counter);$hash=hash_hmac('sha1',$bin,$key,true);$o=ord($hash[19])&15;$n=((ord($hash[$o])&127)<<24)|((ord($hash[$o+1])&255)<<16)|((ord($hash[$o+2])&255)<<8)|(ord($hash[$o+3])&255);return str_pad((string)($n%1000000),6,'0',STR_PAD_LEFT);}
function sn_totp_ok(string $secret,string $code): bool {$t=intdiv(time(),30);for($i=-1;$i<=1;$i++)if(hash_equals(sn_totp($secret,$t+$i),$code))return true;return false;}
function sn_secret(): string {$a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$o='';for($i=0;$i<32;$i++)$o.=$a[random_int(0,31)];return $o;}
$s=$db->prepare('SELECT * FROM user_2fa WHERE user_id=?');$s->execute([$u['id']]);$two=$s->fetch();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='enable'){ $code=trim($_POST['code']??''); if(!$two) { $secret=sn_secret();$db->prepare('INSERT INTO user_2fa(user_id,secret,enabled) VALUES(?,?,0)')->execute([$u['id'],$secret,0]);$two=['user_id'=>$u['id'],'secret'=>$secret,'enabled'=>0]; } if(!sn_totp_ok($two['secret'],$code))$error='Invalid authenticator code.';else{$db->prepare('UPDATE user_2fa SET enabled=1 WHERE user_id=?')->execute([$u['id']]);$msg='Two-factor authentication enabled.';$two['enabled']=1;} }
 if($action==='disable'){ $db->prepare('DELETE FROM user_2fa WHERE user_id=?')->execute([$u['id']]);$two=null;$msg='Two-factor authentication disabled.'; }
}
if(!$two){$secret=sn_secret();$uri='otpauth://totp/SkyNoc:'.rawurlencode($u['email']).'?secret='.$secret.'&issuer=SkyNoc';$displaySecret=$secret;}else{$displaySecret=$two['secret'];$uri='otpauth://totp/SkyNoc:'.rawurlencode($u['email']).'?secret='.$two['secret'].'&issuer=SkyNoc';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Security — SkyNoc</title><style>body{margin:0;background:#f6f8fb;font-family:Inter,system-ui,sans-serif;color:#0f172a}.wrap{max-width:650px;margin:35px auto;padding:15px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:22px}input,button{width:100%;padding:12px;margin:7px 0;box-sizing:border-box}button{background:#111827;color:#fff;border:0;border-radius:9px}.secret{background:#f1f5f9;padding:12px;border-radius:9px;word-break:break-all}.msg{color:#166534;background:#ecfdf5;padding:10px}.err{color:#991b1b;background:#fef2f2;padding:10px}a{color:#111827}</style></head><body><main class="wrap"><div class="card"><a href="<?=$u['role']==='reseller'?'/reseller':'/dashboard'?>">← Back</a><h1>Account Security</h1><?php if($msg):?><p class="msg"><?=e($msg)?></p><?php endif;?><?php if($error):?><p class="err"><?=e($error)?></p><?php endif;?><?php if($two&&$two['enabled']):?><p>2FA is currently <b>enabled</b>.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="disable"><button>Disable 2FA</button></form><?php else:?><p>Scan this secret in Google Authenticator, Authy or another TOTP app.</p><div class="secret"><b>Secret:</b><br><?=e($displaySecret)?><br><small><?=e($uri)?></small></div><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="enable"><input name="code" inputmode="numeric" maxlength="6" placeholder="6-digit code" required><button>Enable 2FA</button></form><?php endif;?></div></main></body></html>