<?php
require __DIR__ . '/../app/bootstrap.php';
$u=require_auth(); $msg=null;$error=null;
$s=$db->prepare('SELECT * FROM user_2fa WHERE user_id=? LIMIT 1');$s->execute([$u['id']]);$two=$s->fetch();
if(!$two){$secret=sn_new_totp_secret();$db->prepare('INSERT INTO user_2fa(user_id,secret,enabled) VALUES(?,?,0)')->execute([$u['id'],$secret]);$two=['user_id'=>$u['id'],'secret'=>$secret,'enabled'=>0];}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=$_POST['action']??'';
 if($action==='enable'){if(!sn_totp_ok($two['secret'],trim((string)($_POST['code']??''))))$error='Invalid authenticator code.';else{$db->prepare('UPDATE user_2fa SET enabled=1 WHERE user_id=?')->execute([$u['id']]);$two['enabled']=1;$msg='Two-factor authentication enabled.';}}
 if($action==='disable'){$db->prepare('DELETE FROM user_2fa WHERE user_id=?')->execute([$u['id']]);$two=null;$msg='Two-factor authentication disabled.';}
}
$secret=$two['secret']??'';$uri='otpauth://totp/SkyNoc:'.rawurlencode($u['email']).'?secret='.$secret.'&issuer=SkyNoc';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Security — SkyNoc</title><style>body{margin:0;background:#f6f8fb;font-family:Inter,system-ui,sans-serif;color:#0f172a}.wrap{max-width:650px;margin:35px auto;padding:15px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:22px}input,button{width:100%;padding:12px;margin:7px 0;box-sizing:border-box}button{background:#111827;color:#fff;border:0;border-radius:9px}.secret{background:#f1f5f9;padding:12px;border-radius:9px;word-break:break-all}.msg{color:#166534;background:#ecfdf5;padding:10px}.err{color:#991b1b;background:#fef2f2;padding:10px}a{color:#111827}</style></head><body><main class="wrap"><div class="card"><a href="<?=$u['role']==='reseller'?'/reseller':'/dashboard'?>">← Back</a><h1>Account Security</h1><?php if($msg):?><p class="msg"><?=e($msg)?></p><?php endif;?><?php if($error):?><p class="err"><?=e($error)?></p><?php endif;?><?php if($two&&$two['enabled']):?><p>2FA is currently <b>enabled</b>.</p><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="disable"><button>Disable 2FA</button></form><?php else:?><p>Scan the secret in Google Authenticator, Authy or another TOTP app.</p><div class="secret"><b>Secret:</b><br><?=e($secret)?><br><small><?=e($uri)?></small></div><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="enable"><input name="code" inputmode="numeric" maxlength="6" placeholder="6-digit code" required><button>Enable 2FA</button></form><?php endif;?></div></main></body></html>