<?php
declare(strict_types=1);
require __DIR__ . '/../app/bootstrap.php';
$cfg=skynoc_telegram_settings();$token=skynoc_telegram_bot_token();$adminIds=skynoc_telegram_admin_chat_ids();
if($_SERVER['REQUEST_METHOD']!=='POST'){
    header('Content-Type: text/plain; charset=utf-8');
    if($token!==''&&$adminIds){http_response_code(200);exit('SkyNoc Telegram webhook is active.');}
    http_response_code(503);exit('SkyNoc Telegram webhook is not configured.');
}
if($token===''||!$adminIds){http_response_code(503);exit('Telegram bot is not configured.');}
$raw=file_get_contents('php://input');$update=json_decode($raw?:'',true);if(!is_array($update)){http_response_code(400);exit('Invalid Telegram update.');}
function tg_update_chat_id(array $u): string{$id=$u['callback_query']['message']['chat']['id']??$u['message']['chat']['id']??'';return (string)$id;}
function tg_is_admin(array $u,array $ids): bool{return in_array(tg_update_chat_id($u),$ids,true);}
function tg_send_client(string $token,string $chat,string $text): bool{return skynoc_telegram_send($token,$chat,$text);}
function skynoc_reissue_fetch(PDO $db,int $id): ?array{$s=$db->prepare('SELECT rr.*,l.license_key,r.name reseller_name,r.email reseller_email FROM reissue_requests rr JOIN licenses l ON l.id=rr.license_id JOIN resellers r ON r.id=rr.reseller_id WHERE rr.id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null;}
function skynoc_reissue_render(array $rr): string{return "📌 <b>LICENSE REISSUE</b>\n\n"."🆔 Request: #".(int)$rr['id']."\n"."👤 Reseller: ".e((string)$rr['reseller_name'])." (#".(int)$rr['reseller_id'].")\n"."📧 Email: ".e((string)$rr['reseller_email'])."\n"."🔑 License: <code>".e((string)$rr['license_key'])."</code>\n"."🌐 Current: ".e((string)($rr['current_domain']?:'-'))."\n"."➡️ New: ".e((string)$rr['new_domain'])."\n"."📝 Reason: ".e((string)($rr['reason']?:'-'))."\n"."📌 Status: <b>".e(strtoupper((string)$rr['status']))."</b>".($rr['admin_note']?"\n🗒 Note: ".e((string)$rr['admin_note']):'');}
if(isset($update['callback_query'])){$cb=$update['callback_query'];$cbId=(string)($cb['id']??'');skynoc_telegram_answer_callback($token,$cbId);if(!tg_is_admin($update,$adminIds)){http_response_code(403);exit('Forbidden.');}$data=(string)($cb['data']??'');if(!preg_match('/^reissue:(\d+):(review|manual_reissue|completed|rejected)$/',$data,$m))exit('OK');$rid=(int)$m[1];$status=$m[2];$rr=skynoc_reissue_fetch($db,$rid);if(!$rr){skynoc_telegram_answer_callback($token,$cbId,'Request not found.');exit('OK');}if(in_array($rr['status'],['completed','rejected'],true)){skynoc_telegram_answer_callback($token,$cbId,'This request is already closed.');exit('OK');}$actor=$db->query("SELECT id,name FROM users WHERE role IN ('owner','admin') AND status='active' ORDER BY CASE role WHEN 'owner' THEN 0 ELSE 1 END,id ASC LIMIT 1")->fetch();if(!$actor)exit('OK');$db->beginTransaction();try{$note='Updated from Telegram admin control.';$db->prepare('UPDATE reissue_requests SET status=?,handled_by=?,admin_note=? WHERE id=?')->execute([$status,(int)$actor['id'],$note,$rid]);if($status==='completed'){$db->prepare('UPDATE licenses SET domain=?,status="active" WHERE id=?')->execute([$rr['new_domain'],$rr['license_id']]);$db->prepare('INSERT INTO license_history(license_id,user_id,action,old_domain,new_domain,notes) VALUES(?,?,?,?,?,?)')->execute([(int)$rr['license_id'],(int)$actor['id'],'reissue_completed',$rr['current_domain'],$rr['new_domain'],$note]);}notify_reseller((int)$rr['reseller_id'],'reissue','Reissue '.$status,'License '.$rr['license_key'].' reissue request is now '.strtoupper($status).'.');$db->commit();audit('telegram_reissue_'.$status,'reissue_requests',$rid,'Telegram admin control');}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log('SkyNoc Telegram reissue error: '.$e->getMessage());skynoc_telegram_answer_callback($token,$cbId,'Update failed.');exit('OK');}$rr=skynoc_reissue_fetch($db,$rid);if($rr){$buttons=in_array($rr['status'],['completed','rejected'],true)?null:skynoc_reissue_buttons($rid);skynoc_telegram_edit($token,(string)$cb['message']['chat']['id'],(int)$cb['message']['message_id'],skynoc_reissue_render($rr),$buttons);}exit('OK');}
$message=$update['message']??[];$chatId=(string)($message['chat']['id']??'');$text=trim((string)($message['text']??''));$isAdmin=in_array($chatId,$adminIds,true);
if($isAdmin){if(preg_match('/^\/reply\s+(-?\d{5,20})\s+(.+)$/s',$text,$m)){tg_send_client($token,$m[1],e((string)$m[2]));skynoc_telegram_send($token,$chatId,'✅ Reply sent to client <code>'.e($m[1]).'</code>.');exit('OK');}if(isset($message['reply_to_message']['text'])&&preg_match('/Client Chat ID:\s*<code>(-?\d{5,20})<\/code>/',$message['reply_to_message']['text'],$m)){if($text!==''){tg_send_client($token,$m[1],e($text));skynoc_telegram_send($token,$chatId,'✅ Client reply sent.');}exit('OK');}if($text==='/start'||$text==='/help'){skynoc_telegram_send($token,$chatId,"🛡 <b>SkyNoc Admin Bot</b>\n\n/reissues — open license reissue requests\n/reissue 123 — show one request\n/reply CHAT_ID message — reply to a client\n\nClient messages are delivered here automatically.");exit('OK');}if($text==='/reissues'){$rows=$db->query("SELECT rr.*,l.license_key,r.name reseller_name,r.email reseller_email FROM reissue_requests rr JOIN licenses l ON l.id=rr.license_id JOIN resellers r ON r.id=rr.reseller_id WHERE rr.status IN ('pending','review','manual_reissue') ORDER BY rr.id DESC LIMIT 10")->fetchAll();if(!$rows)skynoc_telegram_send($token,$chatId,'✅ No open license reissue requests.');else foreach($rows as $rr)skynoc_telegram_send($token,$chatId,skynoc_reissue_render($rr),skynoc_reissue_buttons((int)$rr['id']));exit('OK');}if(preg_match('/^\/reissue\s+(\d+)$/',$text,$m)){$rr=skynoc_reissue_fetch($db,(int)$m[1]);if(!$rr)skynoc_telegram_send($token,$chatId,'❌ Reissue request not found.');else{$buttons=in_array($rr['status'],['completed','rejected'],true)?null:skynoc_reissue_buttons((int)$rr['id']);skynoc_telegram_send($token,$chatId,skynoc_reissue_render($rr),$buttons);}exit('OK');}skynoc_telegram_send($token,$chatId,'Use /reissues to view open license reissue requests.');exit('OK');}
if(!(int)($cfg['support_enabled']??1))exit('OK');
if($text==='/start'){$welcome=trim((string)($cfg['support_welcome']??''));if($welcome==='')$welcome="👋 <b>Welcome to SkyNoc Support</b>\n\nPlease send your message here. Our support team will reply as soon as possible.";tg_send_client($token,$chatId,$welcome);exit('OK');}if($text==='/help'){tg_send_client($token,$chatId,"💬 <b>SkyNoc Support</b>\nSend your question or support message here and our team will respond.");exit('OK');}
$from=$message['from']??[];$name=trim((string)($from['first_name']??'').' '.(string)($from['last_name']??''));$username=(string)($from['username']??'');$display=$name!==''?$name:'Telegram Client';if($username!=='')$display.=' @'.$username;$header="💬 <b>NEW CLIENT SUPPORT MESSAGE</b>\n\n"."👤 Client: ".e($display)."\n"."🆔 Client Chat ID: <code>".e($chatId)."</code>\n"."⏱ Received: ".e(date('Y-m-d H:i:s'))."\n\n";if($text!==''){$header.="📝 <b>Message</b>\n".e($text);foreach($adminIds as $aid)skynoc_telegram_send($token,$aid,$header,['force_reply'=>true,'input_field_placeholder'=>'Reply to this client...']);}else{foreach($adminIds as $aid){skynoc_telegram_send($token,$aid,$header.'📎 <i>Attachment/media received. See the message below.</i>',['force_reply'=>true,'input_field_placeholder'=>'Reply to this client...']);if(isset($message['message_id']))skynoc_telegram_copy_message($token,$aid,$chatId,(int)$message['message_id']);}}exit('OK');
