<?php
declare(strict_types=1);

/** SkyNoc Telegram: one bot for all admin notifications and client support. */
function skynoc_telegram_settings(): array{global $db;$s=$db->query('SELECT * FROM telegram_settings WHERE id=1 LIMIT 1');return $s->fetch()?:[];}
function skynoc_telegram_admin_chat_ids(): array{$cfg=skynoc_telegram_settings();$raw=(string)($cfg['admin_chat_ids']??'');if($raw===''){$raw=(string)($cfg['license_admin_chat_id']??$cfg['admin_chat_id']??'');$legacy=(string)($cfg['deposit_admin_chat_id']??'');if($legacy!=='')$raw.="\n".$legacy;}$ids=[];foreach(preg_split('/[\s,;]+/',$raw)?:[] as $id){$id=trim($id);if($id!==''&&preg_match('/^-?\d{5,20}$/',$id))$ids[$id]=$id;}return array_values($ids);}
function skynoc_telegram_bot_token(): string{$cfg=skynoc_telegram_settings();return trim((string)($cfg['bot_token']??$cfg['license_bot_token']??''));}
function skynoc_telegram_api(string $botToken,string $method,array $payload=[]): array{$botToken=trim($botToken);if($botToken==='')return ['ok'=>false,'description'=>'Telegram bot token is empty.'];$ch=curl_init('https://api.telegram.org/bot'.rawurlencode($botToken).'/'.$method);if($ch===false)return ['ok'=>false,'description'=>'Could not initialize cURL.'];curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$payload,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_HTTPHEADER=>['Expect:']]);$result=curl_exec($ch);$curlError=curl_error($ch);curl_close($ch);if($result===false||$result==='')return ['ok'=>false,'description'=>$curlError!==''?$curlError:'Empty response from Telegram API.'];$json=json_decode($result,true);return is_array($json)?$json:['ok'=>false,'description'=>'Invalid response from Telegram API.'];}
function skynoc_telegram_send(string $botToken,string $chatId,string $text,?array $buttons=null): bool{$chatId=trim($chatId);if($chatId==='')return false;$payload=['chat_id'=>$chatId,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true];if($buttons)$payload['reply_markup']=json_encode($buttons,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$json=skynoc_telegram_api($botToken,'sendMessage',$payload);if(($json['ok']??false)!==true)error_log('SkyNoc Telegram sendMessage failed: '.(string)($json['description']??'Unknown Telegram API error'));return ($json['ok']??false)===true;}
function skynoc_telegram_send_admins(string $text,?array $buttons=null): int{$token=skynoc_telegram_bot_token();if($token==='')return 0;$sent=0;foreach(skynoc_telegram_admin_chat_ids() as $id)if(skynoc_telegram_send($token,$id,$text,$buttons))$sent++;return $sent;}
function skynoc_telegram_test_admins(): array{$token=skynoc_telegram_bot_token();$ids=skynoc_telegram_admin_chat_ids();if($token==='')return ['ok'=>false,'sent'=>0,'total'=>count($ids),'error'=>'Telegram Bot Token is empty.'];if(!$ids)return ['ok'=>false,'sent'=>0,'total'=>0,'error'=>'No admin Chat IDs are configured.'];$me=skynoc_telegram_api($token,'getMe');if(($me['ok']??false)!==true)return ['ok'=>false,'sent'=>0,'total'=>count($ids),'error'=>'Bot token rejected by Telegram: '.(string)($me['description']??'Unknown error')];$sent=0;$errors=[];foreach($ids as $id){$json=skynoc_telegram_api($token,'sendMessage',['chat_id'=>$id,'text'=>"🟢 <b>SkyNoc Telegram Test</b>\n\nUnified bot is working.\n🤖 One bot · 👥 Multiple admins · 💬 Client support",'parse_mode'=>'HTML','disable_web_page_preview'=>true]);if(($json['ok']??false)===true){$sent++;}else{$errors[]=$id.': '.(string)($json['description']??'Unknown Telegram API error');}}return ['ok'=>$sent===count($ids),'sent'=>$sent,'total'=>count($ids),'bot_name'=>(string)($me['result']['username']??$me['result']['first_name']??''),'error'=>$errors?implode(' | ',$errors):''];}
function skynoc_telegram_copy_message(string $botToken,string $toChatId,string $fromChatId,int $messageId): bool{$json=skynoc_telegram_api($botToken,'copyMessage',['chat_id'=>$toChatId,'from_chat_id'=>$fromChatId,'message_id'=>$messageId]);if(($json['ok']??false)!==true)error_log('SkyNoc Telegram copyMessage failed: '.(string)($json['description']??'Unknown Telegram API error'));return ($json['ok']??false)===true;}
function skynoc_telegram_edit(string $botToken,string $chatId,int $messageId,string $text,?array $buttons=null): bool{$payload=['chat_id'=>$chatId,'message_id'=>$messageId,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true];if($buttons)$payload['reply_markup']=json_encode($buttons,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$json=skynoc_telegram_api($botToken,'editMessageText',$payload);return ($json['ok']??false)===true;}
function skynoc_telegram_answer_callback(string $botToken,string $callbackId,string $text=''): bool{if($callbackId==='')return false;$json=skynoc_telegram_api($botToken,'answerCallbackQuery',['callback_query_id'=>$callbackId,'text'=>$text]);return ($json['ok']??false)===true;}
function skynoc_telegram_event_once(string $eventKey): bool{global $db;try{$db->exec("CREATE TABLE IF NOT EXISTS telegram_event_log (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,event_key VARCHAR(191) NOT NULL UNIQUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$q=$db->prepare('INSERT IGNORE INTO telegram_event_log(event_key) VALUES(?)');$q->execute([$eventKey]);return $q->rowCount()===1;}catch(Throwable $e){error_log('SkyNoc Telegram event log error: '.$e->getMessage());return true;}}
function skynoc_license_telegram_send(string $text,?array $buttons=null): bool{return skynoc_telegram_send_admins($text,$buttons)>0;}
function skynoc_deposit_telegram_send(string $text): bool{return skynoc_telegram_send_admins($text)>0;}
function skynoc_reissue_buttons(int $requestId): array{return ['inline_keyboard'=>[[['text'=>'🔎 Review','callback_data'=>'reissue:'.$requestId.':review'],['text'=>'🛠 Manual Reissue','callback_data'=>'reissue:'.$requestId.':manual_reissue']],[['text'=>'✅ Completed','callback_data'=>'reissue:'.$requestId.':completed'],['text'=>'❌ Rejected','callback_data'=>'reissue:'.$requestId.':rejected']]]];}
function skynoc_order_telegram_buttons(int $orderId): array{return ['inline_keyboard'=>[[['text'=>'🔑 Assign License Key','callback_data'=>'order:'.$orderId.':assign'],['text'=>'🔎 View Order','callback_data'=>'order:'.$orderId.':view']],[['text'=>'❌ Reject/Cancel','callback_data'=>'order:'.$orderId.':reject']]]];}
function skynoc_notify_reissue_request(array $rr): bool{$text="🔔 <b>NEW LICENSE REISSUE REQUEST</b>\n\n"."🆔 Request: #".(int)$rr['id']."\n"."👤 Reseller: ".e((string)$rr['reseller_name'])." (#".(int)$rr['reseller_id'].")\n"."📧 Email: ".e((string)$rr['reseller_email'])."\n"."🔑 License: <code>".e((string)$rr['license_key'])."</code>\n"."🌐 Current: ".e((string)($rr['current_domain']?:'-'))."\n"."➡️ New: ".e((string)$rr['new_domain'])."\n"."📝 Reason: ".e((string)($rr['reason']?:'-'))."\n"."📌 Status: <b>".e(strtoupper((string)$rr['status']))."</b>";return skynoc_license_telegram_send($text,skynoc_reissue_buttons((int)$rr['id']));}
