<?php
declare(strict_types=1);

/** SkyNoc Telegram: one bot for all admin notifications and client support. */
function skynoc_telegram_settings(): array{global $db;$s=$db->query('SELECT * FROM telegram_settings WHERE id=1 LIMIT 1');return $s->fetch()?:[];}
function skynoc_telegram_admin_chat_ids(): array{$cfg=skynoc_telegram_settings();$raw=(string)($cfg['admin_chat_ids']??'');if($raw===''){$raw=(string)($cfg['license_admin_chat_id']??$cfg['admin_chat_id']??'');$legacy=(string)($cfg['deposit_admin_chat_id']??'');if($legacy!=='')$raw.="\n".$legacy;}$ids=[];foreach(preg_split('/[\s,;]+/',$raw)?:[] as $id){$id=trim($id);if($id!==''&&preg_match('/^-?\d{5,20}$/',$id))$ids[$id]=$id;}return array_values($ids);}
function skynoc_telegram_bot_token(): string{$cfg=skynoc_telegram_settings();return trim((string)($cfg['bot_token']??$cfg['license_bot_token']??''));}
function skynoc_telegram_send(string $botToken,string $chatId,string $text,?array $buttons=null): bool{$botToken=trim($botToken);$chatId=trim($chatId);if($botToken===''||$chatId==='')return false;$payload=['chat_id'=>$chatId,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true];if($buttons)$payload['reply_markup']=json_encode($buttons,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$ch=curl_init('https://api.telegram.org/bot'.rawurlencode($botToken).'/sendMessage');if($ch===false)return false;curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$payload,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12]);$result=curl_exec($ch);curl_close($ch);$json=is_string($result)?json_decode($result,true):null;return is_array($json)&&($json['ok']??false)===true;}
function skynoc_telegram_send_admins(string $text,?array $buttons=null): int{$token=skynoc_telegram_bot_token();if($token==='')return 0;$sent=0;foreach(skynoc_telegram_admin_chat_ids() as $id)if(skynoc_telegram_send($token,$id,$text,$buttons))$sent++;return $sent;}
function skynoc_telegram_copy_message(string $botToken,string $toChatId,string $fromChatId,int $messageId): bool{$ch=curl_init('https://api.telegram.org/bot'.rawurlencode($botToken).'/copyMessage');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>['chat_id'=>$toChatId,'from_chat_id'=>$fromChatId,'message_id'=>$messageId],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12]);$result=curl_exec($ch);curl_close($ch);$json=is_string($result)?json_decode($result,true):null;return is_array($json)&&($json['ok']??false)===true;}
function skynoc_telegram_edit(string $botToken,string $chatId,int $messageId,string $text,?array $buttons=null): bool{$payload=['chat_id'=>$chatId,'message_id'=>$messageId,'text'=>$text,'parse_mode'=>'HTML','disable_web_page_preview'=>true];if($buttons)$payload['reply_markup']=json_encode($buttons,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$ch=curl_init('https://api.telegram.org/bot'.rawurlencode($botToken).'/editMessageText');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$payload,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12]);$result=curl_exec($ch);curl_close($ch);$json=is_string($result)?json_decode($result,true):null;return is_array($json)&&($json['ok']??false)===true;}
function skynoc_telegram_answer_callback(string $botToken,string $callbackId,string $text=''): bool{if($botToken===''||$callbackId==='')return false;$ch=curl_init('https://api.telegram.org/bot'.rawurlencode($botToken).'/answerCallbackQuery');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>['callback_query_id'=>$callbackId,'text'=>$text],CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>8]);$result=curl_exec($ch);curl_close($ch);$json=is_string($result)?json_decode($result,true):null;return is_array($json)&&($json['ok']??false)===true;}
function skynoc_license_telegram_send(string $text,?array $buttons=null): bool{return skynoc_telegram_send_admins($text,$buttons)>0;}
function skynoc_deposit_telegram_send(string $text): bool{return skynoc_telegram_send_admins($text)>0;}
function skynoc_reissue_buttons(int $requestId): array{return ['inline_keyboard'=>[[['text'=>'🔎 Review','callback_data'=>'reissue:'.$requestId.':review'],['text'=>'🛠 Manual Reissue','callback_data'=>'reissue:'.$requestId.':manual_reissue']],[['text'=>'✅ Completed','callback_data'=>'reissue:'.$requestId.':completed'],['text'=>'❌ Rejected','callback_data'=>'reissue:'.$requestId.':rejected']]]];}
function skynoc_notify_reissue_request(array $rr): bool{$text="🔔 <b>NEW LICENSE REISSUE REQUEST</b>\n\n"."🆔 Request: #".(int)$rr['id']."\n"."👤 Reseller: ".e((string)$rr['reseller_name'])." (#".(int)$rr['reseller_id'].")\n"."📧 Email: ".e((string)$rr['reseller_email'])."\n"."🔑 License: <code>".e((string)$rr['license_key'])."</code>\n"."🌐 Current: ".e((string)($rr['current_domain']?:'-'))."\n"."➡️ New: ".e((string)$rr['new_domain'])."\n"."📝 Reason: ".e((string)($rr['reason']?:'-'))."\n"."📌 Status: <b>".e(strtoupper((string)$rr['status']))."</b>";return skynoc_license_telegram_send($text,skynoc_reissue_buttons((int)$rr['id']));}
