CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('owner','admin','manager','staff','reseller') NOT NULL DEFAULT 'staff',status ENUM('active','suspended','disabled') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE resellers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,name VARCHAR(160) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,status ENUM('active','suspended','disabled') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE provider_accounts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,provider_type VARCHAR(40) NOT NULL DEFAULT 'MANUAL_PARTNER',provider_name VARCHAR(120) NOT NULL,account_email VARCHAR(190) NULL,account_label VARCHAR(120) NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',internal_notes TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE licenses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,provider_account_id BIGINT UNSIGNED NULL,license_key VARCHAR(255) NOT NULL UNIQUE,domain VARCHAR(255) NULL,reseller_id BIGINT UNSIGNED NULL,status ENUM('available','active','suspended','expired','cancelled') NOT NULL DEFAULT 'available',purchase_date DATE NULL,cost DECIMAL(12,2) NULL,expires_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(provider_account_id) REFERENCES provider_accounts(id) ON DELETE SET NULL,FOREIGN KEY(reseller_id) REFERENCES resellers(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE license_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,license_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,action VARCHAR(60) NOT NULL,old_domain VARCHAR(255) NULL,new_domain VARCHAR(255) NULL,notes TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(license_id) REFERENCES licenses(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE reissue_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,license_id BIGINT UNSIGNED NOT NULL,reseller_id BIGINT UNSIGNED NOT NULL,current_domain VARCHAR(255) NULL,new_domain VARCHAR(255) NOT NULL,reason TEXT NULL,status ENUM('pending','review','manual_reissue','completed','rejected') NOT NULL DEFAULT 'pending',handled_by BIGINT UNSIGNED NULL,admin_note TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(license_id) REFERENCES licenses(id) ON DELETE CASCADE,FOREIGN KEY(reseller_id) REFERENCES resellers(id) ON DELETE CASCADE,FOREIGN KEY(handled_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE api_keys (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,reseller_id BIGINT UNSIGNED NOT NULL,name VARCHAR(100) NOT NULL,key_prefix VARCHAR(20) NOT NULL,key_hash CHAR(64) NOT NULL UNIQUE,status ENUM('active','revoked','suspended') NOT NULL DEFAULT 'active',last_used_at DATETIME NULL,expires_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(reseller_id) REFERENCES resellers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE tickets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,reseller_id BIGINT UNSIGNED NULL,subject VARCHAR(255) NOT NULL,status ENUM('open','pending','closed') NOT NULL DEFAULT 'open',priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(reseller_id) REFERENCES resellers(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE ticket_messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,action VARCHAR(100) NOT NULL,entity VARCHAR(80) NULL,entity_id BIGINT UNSIGNED NULL,details TEXT NULL,ip_address VARCHAR(45) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE telegram_settings (id TINYINT UNSIGNED PRIMARY KEY,bot_token VARCHAR(255) NOT NULL,admin_chat_id VARCHAR(64) NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_license_reseller ON licenses(reseller_id); CREATE INDEX idx_reissue_status ON reissue_requests(status); CREATE INDEX idx_audit_created ON audit_logs(created_at); CREATE INDEX idx_api_reseller_status ON api_keys(reseller_id,status);

-- Phase 1 production additions
ALTER TABLE users ADD COLUMN permissions JSON NULL AFTER status;
ALTER TABLE api_keys ADD COLUMN scopes VARCHAR(255) NOT NULL DEFAULT 'licenses:read,reissue:create,reissue:read' AFTER key_hash;
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 reseller_id BIGINT UNSIGNED NOT NULL,
 type VARCHAR(60) NOT NULL,
 title VARCHAR(255) NOT NULL,
 message TEXT NOT NULL,
 read_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(reseller_id) REFERENCES resellers(id) ON DELETE CASCADE,
 INDEX idx_notifications_reseller_read (reseller_id,read_at),
 INDEX idx_notifications_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS api_rate_limits (
 api_key_id BIGINT UNSIGNED PRIMARY KEY,
 window_started_at DATETIME NOT NULL,
 request_count INT UNSIGNED NOT NULL DEFAULT 0,
 FOREIGN KEY(api_key_id) REFERENCES api_keys(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
